/**
 * AUTOMATISCH ERZEUGT von scripts/build-ratgeber-registry.mjs. Nicht von Hand
 * bearbeiten: Quelle sind die Inhaltsdateien und gliederung.js (Ablauf für
 * neue Artikel dort im Kopfkommentar).
 *
 * Je veröffentlichtem Slug ein dynamischer Import. Vite legt dadurch jede
 * Inhaltsdatei in einen eigenen Chunk, und eine Artikelseite lädt nur ihren.
 * Nur src/pages/RatgeberArtikelPage.jsx importiert diese Datei.
 */

export const RATGEBER_LOADERS = new Map([
  ['schwangerschaft-worauf-achten', () => import('./schwangerschaft-worauf-achten.js')],
  ['bonusprogramm-krankenkasse', () => import('./bonusprogramm-krankenkasse.js')],
  ['ikk-classic-bonusprogramm-2026', () => import('./ikk-classic-bonusprogramm-2026.js')],
  ['mkk-bonusprogramm-2026', () => import('./mkk-bonusprogramm-2026.js')],
  ['aok-bonusprogramm-2026', () => import('./aok-bonusprogramm-2026.js')],
  ['tk-bonusprogramm-2026', () => import('./tk-bonusprogramm-2026.js')],
  ['barmer-bonusprogramm-2026', () => import('./barmer-bonusprogramm-2026.js')],
  ['krankenkassen-bonus-zusatzversicherung', () => import('./krankenkassen-bonus-zusatzversicherung.js')],
  ['zusatzbeitrag-krankenkasse-2026', () => import('./zusatzbeitrag-krankenkasse-2026.js')],
  ['krankenkasse-wechseln', () => import('./krankenkasse-wechseln.js')],
  ['aok-zuzahlungsbefreiung', () => import('./aok-zuzahlungsbefreiung.js')],
  ['zusatzbeitrag-rentner', () => import('./zusatzbeitrag-rentner.js')],
  ['praeventionskurs-krankenkasse', () => import('./praeventionskurs-krankenkasse.js')],
  ['guenstigste-krankenkasse', () => import('./guenstigste-krankenkasse.js')],
  ['mindestbeitrag-krankenkasse', () => import('./mindestbeitrag-krankenkasse.js')],
  ['dak-zuzahlungsbefreiung', () => import('./dak-zuzahlungsbefreiung.js')],
  ['krankenkasse-studenten', () => import('./krankenkasse-studenten.js')],
  ['dak-bonusprogramm-2026', () => import('./dak-bonusprogramm-2026.js')],
  ['krankenkasse-zuschuss-fitnessstudio', () => import('./krankenkasse-zuschuss-fitnessstudio.js')],
  ['zuzahlungsbefreiung-chronisch-krank', () => import('./zuzahlungsbefreiung-chronisch-krank.js')],
  ['ikk-zuzahlungsbefreiung', () => import('./ikk-zuzahlungsbefreiung.js')],
  ['zuzahlung-medikamente', () => import('./zuzahlung-medikamente.js')],
  ['krankenkasse-wechseln-nachteile', () => import('./krankenkasse-wechseln-nachteile.js')],
  ['zuzahlungsbefreiung-schwerbehinderung', () => import('./zuzahlungsbefreiung-schwerbehinderung.js')],
  ['wechselpraemie-krankenkasse', () => import('./wechselpraemie-krankenkasse.js')],
  ['hkk-bonusprogramm-2026', () => import('./hkk-bonusprogramm-2026.js')],
  ['hek-bonusprogramm-2026', () => import('./hek-bonusprogramm-2026.js')],
  ['abnehmen-krankenkasse', () => import('./abnehmen-krankenkasse.js')],
  ['beitragserhoehung-krankenkasse', () => import('./beitragserhoehung-krankenkasse.js')],
  ['mobil-krankenkasse-bonusprogramm', () => import('./mobil-krankenkasse-bonusprogramm.js')],
  ['zuzahlungsbefreiung', () => import('./zuzahlungsbefreiung.js')],
  ['krankenversicherung-beitrag-2026', () => import('./krankenversicherung-beitrag-2026.js')],
  ['tk-zuzahlungsbefreiung', () => import('./tk-zuzahlungsbefreiung.js')],
  ['barmer-zuzahlungsbefreiung', () => import('./barmer-zuzahlungsbefreiung.js')],
  ['zuzahlungsbefreiung-rentner', () => import('./zuzahlungsbefreiung-rentner.js')],
  ['bkk-firmus-bonusprogramm-2026', () => import('./bkk-firmus-bonusprogramm-2026.js')],
  ['krankenkasse-wechseln-rentner', () => import('./krankenkasse-wechseln-rentner.js')],
  ['zahnersatz-kosten', () => import('./zahnersatz-kosten.js')],
  ['professionelle-zahnreinigung-kosten', () => import('./professionelle-zahnreinigung-kosten.js')],
  ['zahnimplantat-kosten', () => import('./zahnimplantat-kosten.js')],
  ['wurzelbehandlung-kosten', () => import('./wurzelbehandlung-kosten.js')],
  ['zahnkrone-kosten', () => import('./zahnkrone-kosten.js')],
  ['bonusheft-zahnarzt', () => import('./bonusheft-zahnarzt.js')],
  ['zahnzusatzversicherung-ohne-wartezeit', () => import('./zahnzusatzversicherung-ohne-wartezeit.js')],
  ['zahnzusatzversicherung-fehlender-zahn', () => import('./zahnzusatzversicherung-fehlender-zahn.js')],
  ['zahnzusatzversicherung-lohnt-sich', () => import('./zahnzusatzversicherung-lohnt-sich.js')],
  ['ukv-zahnzusatzversicherung', () => import('./ukv-zahnzusatzversicherung.js')],
  ['bayerische-zahnzusatzversicherung', () => import('./bayerische-zahnzusatzversicherung.js')],
  ['aok-zahnzusatzversicherung', () => import('./aok-zahnzusatzversicherung.js')],
  ['dak-zahnreinigung', () => import('./dak-zahnreinigung.js')],
  ['zahnbruecke-kosten', () => import('./zahnbruecke-kosten.js')],
  ['zahnprothese-kosten', () => import('./zahnprothese-kosten.js')],
  ['zahnfuellung-kosten', () => import('./zahnfuellung-kosten.js')],
  ['parodontitis-behandlung-kosten', () => import('./parodontitis-behandlung-kosten.js')],
  ['zahnersatz-moeglichkeiten', () => import('./zahnersatz-moeglichkeiten.js')],
  ['zahnersatz-haertefall', () => import('./zahnersatz-haertefall.js')],
  ['zahnzusatzversicherung-vergleich', () => import('./zahnzusatzversicherung-vergleich.js')],
  ['aok-zahnreinigung', () => import('./aok-zahnreinigung.js')],
  ['tk-zahnreinigung', () => import('./tk-zahnreinigung.js')],
  ['barmer-zahnreinigung', () => import('./barmer-zahnreinigung.js')],
  ['tk-zahnzusatzversicherung', () => import('./tk-zahnzusatzversicherung.js')],
  ['zahnzusatzversicherung-kosten', () => import('./zahnzusatzversicherung-kosten.js')],
  ['zahnzusatzversicherung-laufende-behandlung', () => import('./zahnzusatzversicherung-laufende-behandlung.js')],
  ['professionelle-zahnreinigung-sinnvoll', () => import('./professionelle-zahnreinigung-sinnvoll.js')],
  ['zahnreinigung-wie-oft', () => import('./zahnreinigung-wie-oft.js')],
  ['weisheitszaehne-ziehen-kosten', () => import('./weisheitszaehne-ziehen-kosten.js')],
  ['vollnarkose-zahnarzt-kosten', () => import('./vollnarkose-zahnarzt-kosten.js')],
  ['barmer-zahnzusatzversicherung', () => import('./barmer-zahnzusatzversicherung.js')],
  ['zahnkrone-rausgefallen', () => import('./zahnkrone-rausgefallen.js')],
  ['dak-zahnzusatzversicherung', () => import('./dak-zahnzusatzversicherung.js')],
  ['ikk-zahnreinigung', () => import('./ikk-zahnreinigung.js')],
  ['zahnersatz-guenstig', () => import('./zahnersatz-guenstig.js')],
  ['heil-und-kostenplan', () => import('./heil-und-kostenplan.js')],
  ['zahnzusatzversicherung-senioren', () => import('./zahnzusatzversicherung-senioren.js')],
  ['implantat-oder-bruecke', () => import('./implantat-oder-bruecke.js')],
  ['ikk-zahnzusatzversicherung', () => import('./ikk-zahnzusatzversicherung.js')],
  ['zahnzusatzversicherung-kinder', () => import('./zahnzusatzversicherung-kinder.js')],
  ['zahnspange-kosten', () => import('./zahnspange-kosten.js')],
  ['zahnspange-erwachsene', () => import('./zahnspange-erwachsene.js')],
  ['unsichtbare-zahnspange-kosten', () => import('./unsichtbare-zahnspange-kosten.js')],
  ['zahnzusatzversicherung-kieferorthopaedie', () => import('./zahnzusatzversicherung-kieferorthopaedie.js')],
  ['zahnzusatzversicherung-familie', () => import('./zahnzusatzversicherung-familie.js')],
  ['heilpraktiker-kosten', () => import('./heilpraktiker-kosten.js')],
  ['heilpraktiker-zusatzversicherung', () => import('./heilpraktiker-zusatzversicherung.js')],
  ['ambulante-zusatzversicherung', () => import('./ambulante-zusatzversicherung.js')],
  ['akupunktur-kosten', () => import('./akupunktur-kosten.js')],
  ['tk-osteopathie', () => import('./tk-osteopathie.js')],
  ['chiropraktiker-kosten', () => import('./chiropraktiker-kosten.js')],
  ['physiotherapie-zuzahlung', () => import('./physiotherapie-zuzahlung.js')],
  ['gebuehrenordnung-heilpraktiker', () => import('./gebuehrenordnung-heilpraktiker.js')],
  ['osteopathie-kosten', () => import('./osteopathie-kosten.js')],
  ['naturheilkunde', () => import('./naturheilkunde.js')],
  ['osteopathie-krankenkasse', () => import('./osteopathie-krankenkasse.js')],
  ['physiotherapie-kosten', () => import('./physiotherapie-kosten.js')],
  ['akupunktur-krankenkasse', () => import('./akupunktur-krankenkasse.js')],
  ['aok-osteopathie', () => import('./aok-osteopathie.js')],
  ['tcm-krankenkasse', () => import('./tcm-krankenkasse.js')],
  ['aok-heilpraktiker', () => import('./aok-heilpraktiker.js')],
  ['zusatzversicherung-osteopathie', () => import('./zusatzversicherung-osteopathie.js')],
  ['heilpraktiker-zusatzversicherung-ohne-wartezeit', () => import('./heilpraktiker-zusatzversicherung-ohne-wartezeit.js')],
  ['barmer-osteopathie', () => import('./barmer-osteopathie.js')],
  ['tk-heilpraktiker', () => import('./tk-heilpraktiker.js')],
  ['mobil-krankenkasse-osteopathie', () => import('./mobil-krankenkasse-osteopathie.js')],
  ['stationaere-zusatzversicherung', () => import('./stationaere-zusatzversicherung.js')],
  ['einzelzimmer-krankenhaus-kosten', () => import('./einzelzimmer-krankenhaus-kosten.js')],
  ['zusatzversicherung-einzelzimmer', () => import('./zusatzversicherung-einzelzimmer.js')],
  ['krankenhaustagegeld', () => import('./krankenhaustagegeld.js')],
  ['reha-zuzahlung', () => import('./reha-zuzahlung.js')],
  ['krankenhauszusatzversicherung-vergleich', () => import('./krankenhauszusatzversicherung-vergleich.js')],
  ['chefarztbehandlung', () => import('./chefarztbehandlung.js')],
  ['krankenhauszusatzversicherung-kosten', () => import('./krankenhauszusatzversicherung-kosten.js')],
  ['krankenhauszusatzversicherung-ohne-wartezeit', () => import('./krankenhauszusatzversicherung-ohne-wartezeit.js')],
  ['begleitperson-krankenhaus', () => import('./begleitperson-krankenhaus.js')],
  ['aok-krankenhauszusatzversicherung', () => import('./aok-krankenhauszusatzversicherung.js')],
  ['tk-krankenhauszusatzversicherung', () => import('./tk-krankenhauszusatzversicherung.js')],
  ['krankenhauszusatzversicherung-vorerkrankung', () => import('./krankenhauszusatzversicherung-vorerkrankung.js')],
  ['krankenhauszusatzversicherung-kinder', () => import('./krankenhauszusatzversicherung-kinder.js')],
  ['krankenhauszusatzversicherung-senioren', () => import('./krankenhauszusatzversicherung-senioren.js')],
  ['zusatzversicherung-kinder', () => import('./zusatzversicherung-kinder.js')],
  ['baby-geplant-zusatzversicherung', () => import('./baby-geplant-zusatzversicherung.js')],
  ['neugeborenes-versichern', () => import('./neugeborenes-versichern.js')],
  ['familienzimmer-krankenhaus', () => import('./familienzimmer-krankenhaus.js')],
  ['babybonus-krankenkasse', () => import('./babybonus-krankenkasse.js')],
  ['hebamme-rufbereitschaft', () => import('./hebamme-rufbereitschaft.js')],
  ['schwanger-zusatzversicherung', () => import('./schwanger-zusatzversicherung.js')],
  ['schwangerschaft-was-steht-mir-zu', () => import('./schwangerschaft-was-steht-mir-zu.js')],
  ['hebamme-kosten-krankenkasse', () => import('./hebamme-kosten-krankenkasse.js')],
  ['geburtsvorbereitungskurs', () => import('./geburtsvorbereitungskurs.js')],
  ['familienversicherung-krankenkasse', () => import('./familienversicherung-krankenkasse.js')],
  ['aok-babybonus', () => import('./aok-babybonus.js')],
  ['geburtsvorbereitungskurs-partner', () => import('./geburtsvorbereitungskurs-partner.js')],
  ['schwangerschaft-krankenkasse-melden', () => import('./schwangerschaft-krankenkasse-melden.js')],
  ['tk-schwangerschaft', () => import('./tk-schwangerschaft.js')],
  ['vorsorgeuntersuchung', () => import('./vorsorgeuntersuchung.js')],
  ['vorsorgeuntersuchung-frauen', () => import('./vorsorgeuntersuchung-frauen.js')],
  ['vorsorgeuntersuchung-maenner', () => import('./vorsorgeuntersuchung-maenner.js')],
  ['hautkrebsscreening', () => import('./hautkrebsscreening.js')],
  ['tk-reiseimpfung', () => import('./tk-reiseimpfung.js')],
  ['check-up-35', () => import('./check-up-35.js')],
  ['reiseimpfung-krankenkasse', () => import('./reiseimpfung-krankenkasse.js')],
  ['tk-hautkrebsscreening', () => import('./tk-hautkrebsscreening.js')],
  ['vorsorgeuntersuchungen-kinder', () => import('./vorsorgeuntersuchungen-kinder.js')],
  ['aok-reiseimpfung', () => import('./aok-reiseimpfung.js')],
  ['brille-krankenkasse', () => import('./brille-krankenkasse.js')],
  ['brillenversicherung', () => import('./brillenversicherung.js')],
  ['gleitsichtbrille-kosten', () => import('./gleitsichtbrille-kosten.js')],
  ['augenlasern-kosten', () => import('./augenlasern-kosten.js')],
  ['brillenversicherung-kinder', () => import('./brillenversicherung-kinder.js')],
  ['tk-brille', () => import('./tk-brille.js')],
  ['aok-brille', () => import('./aok-brille.js')],
  ['kontaktlinsen-krankenkasse', () => import('./kontaktlinsen-krankenkasse.js')],
  ['brille-verloren-versicherung', () => import('./brille-verloren-versicherung.js')],
  ['brillenkosten', () => import('./brillenkosten.js')],
  ['zahn-und-brillenversicherung', () => import('./zahn-und-brillenversicherung.js')],
  ['altersvorsorgedepot-was-ist-das', () => import('./altersvorsorgedepot-was-ist-das.js')],
  ['altersvorsorgedepot-ab-wann', () => import('./altersvorsorgedepot-ab-wann.js')],
  ['altersvorsorgedepot-foerderung', () => import('./altersvorsorgedepot-foerderung.js')],
  ['altersvorsorgedepot-wer-ist-berechtigt', () => import('./altersvorsorgedepot-wer-ist-berechtigt.js')],
  ['riester-altersvorsorgedepot-wechsel', () => import('./riester-altersvorsorgedepot-wechsel.js')],
  ['riester-kuendigen-oder-behalten', () => import('./riester-kuendigen-oder-behalten.js')],
  ['riester-jahresmitteilung-checkliste', () => import('./riester-jahresmitteilung-checkliste.js')],
  ['riester-alte-oder-neue-foerderung', () => import('./riester-alte-oder-neue-foerderung.js')],
  ['altersvorsorgedepot-kinderzulage', () => import('./altersvorsorgedepot-kinderzulage.js')],
  ['altersvorsorgedepot-kinderzulage-elternteil', () => import('./altersvorsorgedepot-kinderzulage-elternteil.js')],
  ['altersvorsorgedepot-teilzeit-elternzeit', () => import('./altersvorsorgedepot-teilzeit-elternzeit.js')],
  ['altersvorsorgedepot-kindergeld-ende', () => import('./altersvorsorgedepot-kindergeld-ende.js')],
  ['altersvorsorgedepot-selbststaendige', () => import('./altersvorsorgedepot-selbststaendige.js')],
  ['altersvorsorgedepot-schwankendes-einkommen', () => import('./altersvorsorgedepot-schwankendes-einkommen.js')],
  ['altersvorsorgedepot-heilpraktiker', () => import('./altersvorsorgedepot-heilpraktiker.js')],
  ['altersvorsorgedepot-oder-ruerup', () => import('./altersvorsorgedepot-oder-ruerup.js')],
  ['altersvorsorgedepot-kosten', () => import('./altersvorsorgedepot-kosten.js')],
  ['altersvorsorgedepot-garantie', () => import('./altersvorsorgedepot-garantie.js')],
  ['altersvorsorgedepot-etf-sparplan', () => import('./altersvorsorgedepot-etf-sparplan.js')],
  ['altersvorsorgedepot-steuern', () => import('./altersvorsorgedepot-steuern.js')],
  ['altersvorsorgedepot-geld-entnehmen', () => import('./altersvorsorgedepot-geld-entnehmen.js')],
  ['altersvorsorgedepot-auszahlung', () => import('./altersvorsorgedepot-auszahlung.js')],
  ['altersvorsorgedepot-anbieterwechsel', () => import('./altersvorsorgedepot-anbieterwechsel.js')],
  ['altersvorsorgedepot-passt-das-zu-mir', () => import('./altersvorsorgedepot-passt-das-zu-mir.js')],
]);

// Themengruppe je Slug (nur Artikel mit Gruppe). Die Vorlage wählt damit die
// Rechner-Karte am Ende des Artikels (src/content/ratgeber/rechnerWege.js),
// ohne die Gliederung oder das Register zu laden.
export const RATGEBER_GROUP_OF = new Map([
  ['bonusprogramm-krankenkasse', 'kasse-bonus'],
  ['ikk-classic-bonusprogramm-2026', 'kasse-bonus'],
  ['mkk-bonusprogramm-2026', 'kasse-bonus'],
  ['aok-bonusprogramm-2026', 'kasse-bonus'],
  ['tk-bonusprogramm-2026', 'kasse-bonus'],
  ['barmer-bonusprogramm-2026', 'kasse-bonus'],
  ['krankenkassen-bonus-zusatzversicherung', 'kasse-bonus'],
  ['zusatzbeitrag-krankenkasse-2026', 'kasse-bonus'],
  ['krankenkasse-wechseln', 'kasse-bonus'],
  ['aok-zuzahlungsbefreiung', 'kasse-bonus'],
  ['zusatzbeitrag-rentner', 'kasse-bonus'],
  ['praeventionskurs-krankenkasse', 'kasse-bonus'],
  ['guenstigste-krankenkasse', 'kasse-bonus'],
  ['mindestbeitrag-krankenkasse', 'kasse-bonus'],
  ['dak-zuzahlungsbefreiung', 'kasse-bonus'],
  ['krankenkasse-studenten', 'kasse-bonus'],
  ['dak-bonusprogramm-2026', 'kasse-bonus'],
  ['krankenkasse-zuschuss-fitnessstudio', 'kasse-bonus'],
  ['zuzahlungsbefreiung-chronisch-krank', 'kasse-bonus'],
  ['ikk-zuzahlungsbefreiung', 'kasse-bonus'],
  ['zuzahlung-medikamente', 'kasse-bonus'],
  ['krankenkasse-wechseln-nachteile', 'kasse-bonus'],
  ['zuzahlungsbefreiung-schwerbehinderung', 'kasse-bonus'],
  ['wechselpraemie-krankenkasse', 'kasse-bonus'],
  ['hkk-bonusprogramm-2026', 'kasse-bonus'],
  ['hek-bonusprogramm-2026', 'kasse-bonus'],
  ['abnehmen-krankenkasse', 'kasse-bonus'],
  ['beitragserhoehung-krankenkasse', 'kasse-bonus'],
  ['mobil-krankenkasse-bonusprogramm', 'kasse-bonus'],
  ['zuzahlungsbefreiung', 'kasse-bonus'],
  ['krankenversicherung-beitrag-2026', 'kasse-bonus'],
  ['tk-zuzahlungsbefreiung', 'kasse-bonus'],
  ['barmer-zuzahlungsbefreiung', 'kasse-bonus'],
  ['zuzahlungsbefreiung-rentner', 'kasse-bonus'],
  ['bkk-firmus-bonusprogramm-2026', 'kasse-bonus'],
  ['krankenkasse-wechseln-rentner', 'kasse-bonus'],
  ['zahnersatz-kosten', 'zaehne'],
  ['professionelle-zahnreinigung-kosten', 'zaehne'],
  ['zahnimplantat-kosten', 'zaehne'],
  ['wurzelbehandlung-kosten', 'zaehne'],
  ['zahnkrone-kosten', 'zaehne'],
  ['bonusheft-zahnarzt', 'zaehne'],
  ['zahnzusatzversicherung-ohne-wartezeit', 'zaehne'],
  ['zahnzusatzversicherung-fehlender-zahn', 'zaehne'],
  ['zahnzusatzversicherung-lohnt-sich', 'zaehne'],
  ['ukv-zahnzusatzversicherung', 'zaehne'],
  ['bayerische-zahnzusatzversicherung', 'zaehne'],
  ['aok-zahnzusatzversicherung', 'zaehne'],
  ['dak-zahnreinigung', 'zaehne'],
  ['zahnbruecke-kosten', 'zaehne'],
  ['zahnprothese-kosten', 'zaehne'],
  ['zahnfuellung-kosten', 'zaehne'],
  ['parodontitis-behandlung-kosten', 'zaehne'],
  ['zahnersatz-moeglichkeiten', 'zaehne'],
  ['zahnersatz-haertefall', 'zaehne'],
  ['zahnzusatzversicherung-vergleich', 'zaehne'],
  ['aok-zahnreinigung', 'zaehne'],
  ['tk-zahnreinigung', 'zaehne'],
  ['barmer-zahnreinigung', 'zaehne'],
  ['tk-zahnzusatzversicherung', 'zaehne'],
  ['zahnzusatzversicherung-kosten', 'zaehne'],
  ['zahnzusatzversicherung-laufende-behandlung', 'zaehne'],
  ['professionelle-zahnreinigung-sinnvoll', 'zaehne'],
  ['zahnreinigung-wie-oft', 'zaehne'],
  ['weisheitszaehne-ziehen-kosten', 'zaehne'],
  ['vollnarkose-zahnarzt-kosten', 'zaehne'],
  ['barmer-zahnzusatzversicherung', 'zaehne'],
  ['zahnkrone-rausgefallen', 'zaehne'],
  ['dak-zahnzusatzversicherung', 'zaehne'],
  ['ikk-zahnreinigung', 'zaehne'],
  ['zahnersatz-guenstig', 'zaehne'],
  ['heil-und-kostenplan', 'zaehne'],
  ['zahnzusatzversicherung-senioren', 'zaehne'],
  ['implantat-oder-bruecke', 'zaehne'],
  ['ikk-zahnzusatzversicherung', 'zaehne'],
  ['zahnzusatzversicherung-kinder', 'zaehne'],
  ['zahnspange-kosten', 'zaehne'],
  ['zahnspange-erwachsene', 'zaehne'],
  ['unsichtbare-zahnspange-kosten', 'zaehne'],
  ['zahnzusatzversicherung-kieferorthopaedie', 'zaehne'],
  ['zahnzusatzversicherung-familie', 'zaehne'],
  ['heilpraktiker-kosten', 'ambulant'],
  ['heilpraktiker-zusatzversicherung', 'ambulant'],
  ['ambulante-zusatzversicherung', 'ambulant'],
  ['akupunktur-kosten', 'ambulant'],
  ['tk-osteopathie', 'ambulant'],
  ['chiropraktiker-kosten', 'ambulant'],
  ['physiotherapie-zuzahlung', 'ambulant'],
  ['gebuehrenordnung-heilpraktiker', 'ambulant'],
  ['osteopathie-kosten', 'ambulant'],
  ['naturheilkunde', 'ambulant'],
  ['osteopathie-krankenkasse', 'ambulant'],
  ['physiotherapie-kosten', 'ambulant'],
  ['akupunktur-krankenkasse', 'ambulant'],
  ['aok-osteopathie', 'ambulant'],
  ['tcm-krankenkasse', 'ambulant'],
  ['aok-heilpraktiker', 'ambulant'],
  ['zusatzversicherung-osteopathie', 'ambulant'],
  ['heilpraktiker-zusatzversicherung-ohne-wartezeit', 'ambulant'],
  ['barmer-osteopathie', 'ambulant'],
  ['tk-heilpraktiker', 'ambulant'],
  ['mobil-krankenkasse-osteopathie', 'ambulant'],
  ['stationaere-zusatzversicherung', 'krankenhaus'],
  ['einzelzimmer-krankenhaus-kosten', 'krankenhaus'],
  ['zusatzversicherung-einzelzimmer', 'krankenhaus'],
  ['krankenhaustagegeld', 'krankenhaus'],
  ['reha-zuzahlung', 'krankenhaus'],
  ['krankenhauszusatzversicherung-vergleich', 'krankenhaus'],
  ['chefarztbehandlung', 'krankenhaus'],
  ['krankenhauszusatzversicherung-kosten', 'krankenhaus'],
  ['krankenhauszusatzversicherung-ohne-wartezeit', 'krankenhaus'],
  ['begleitperson-krankenhaus', 'krankenhaus'],
  ['aok-krankenhauszusatzversicherung', 'krankenhaus'],
  ['tk-krankenhauszusatzversicherung', 'krankenhaus'],
  ['krankenhauszusatzversicherung-vorerkrankung', 'krankenhaus'],
  ['krankenhauszusatzversicherung-kinder', 'krankenhaus'],
  ['krankenhauszusatzversicherung-senioren', 'krankenhaus'],
  ['zusatzversicherung-kinder', 'familie'],
  ['baby-geplant-zusatzversicherung', 'familie'],
  ['neugeborenes-versichern', 'familie'],
  ['familienzimmer-krankenhaus', 'familie'],
  ['babybonus-krankenkasse', 'familie'],
  ['hebamme-rufbereitschaft', 'familie'],
  ['schwanger-zusatzversicherung', 'familie'],
  ['schwangerschaft-was-steht-mir-zu', 'familie'],
  ['hebamme-kosten-krankenkasse', 'familie'],
  ['geburtsvorbereitungskurs', 'familie'],
  ['familienversicherung-krankenkasse', 'familie'],
  ['aok-babybonus', 'familie'],
  ['geburtsvorbereitungskurs-partner', 'familie'],
  ['schwangerschaft-krankenkasse-melden', 'familie'],
  ['tk-schwangerschaft', 'familie'],
  ['vorsorgeuntersuchung', 'vorsorge'],
  ['vorsorgeuntersuchung-frauen', 'vorsorge'],
  ['vorsorgeuntersuchung-maenner', 'vorsorge'],
  ['hautkrebsscreening', 'vorsorge'],
  ['tk-reiseimpfung', 'vorsorge'],
  ['check-up-35', 'vorsorge'],
  ['reiseimpfung-krankenkasse', 'vorsorge'],
  ['tk-hautkrebsscreening', 'vorsorge'],
  ['vorsorgeuntersuchungen-kinder', 'vorsorge'],
  ['aok-reiseimpfung', 'vorsorge'],
  ['brille-krankenkasse', 'brille'],
  ['brillenversicherung', 'brille'],
  ['gleitsichtbrille-kosten', 'brille'],
  ['augenlasern-kosten', 'brille'],
  ['brillenversicherung-kinder', 'brille'],
  ['tk-brille', 'brille'],
  ['aok-brille', 'brille'],
  ['kontaktlinsen-krankenkasse', 'brille'],
  ['brille-verloren-versicherung', 'brille'],
  ['brillenkosten', 'brille'],
  ['zahn-und-brillenversicherung', 'brille'],
  ['altersvorsorgedepot-was-ist-das', 'altersvorsorge'],
  ['altersvorsorgedepot-ab-wann', 'altersvorsorge'],
  ['altersvorsorgedepot-foerderung', 'altersvorsorge'],
  ['altersvorsorgedepot-wer-ist-berechtigt', 'altersvorsorge'],
  ['riester-altersvorsorgedepot-wechsel', 'altersvorsorge'],
  ['riester-kuendigen-oder-behalten', 'altersvorsorge'],
  ['riester-jahresmitteilung-checkliste', 'altersvorsorge'],
  ['riester-alte-oder-neue-foerderung', 'altersvorsorge'],
  ['altersvorsorgedepot-kinderzulage', 'altersvorsorge'],
  ['altersvorsorgedepot-kinderzulage-elternteil', 'altersvorsorge'],
  ['altersvorsorgedepot-teilzeit-elternzeit', 'altersvorsorge'],
  ['altersvorsorgedepot-kindergeld-ende', 'altersvorsorge'],
  ['altersvorsorgedepot-selbststaendige', 'altersvorsorge'],
  ['altersvorsorgedepot-schwankendes-einkommen', 'altersvorsorge'],
  ['altersvorsorgedepot-heilpraktiker', 'altersvorsorge'],
  ['altersvorsorgedepot-oder-ruerup', 'altersvorsorge'],
  ['altersvorsorgedepot-kosten', 'altersvorsorge'],
  ['altersvorsorgedepot-garantie', 'altersvorsorge'],
  ['altersvorsorgedepot-etf-sparplan', 'altersvorsorge'],
  ['altersvorsorgedepot-steuern', 'altersvorsorge'],
  ['altersvorsorgedepot-geld-entnehmen', 'altersvorsorge'],
  ['altersvorsorgedepot-auszahlung', 'altersvorsorge'],
  ['altersvorsorgedepot-anbieterwechsel', 'altersvorsorge'],
  ['altersvorsorgedepot-passt-das-zu-mir', 'altersvorsorge'],
]);
