/**
 * AUTOMATISCH ERZEUGT von scripts/build-ratgeber-registry.mjs. Nicht von Hand
 * bearbeiten: Quelle sind die Inhaltsdateien und gliederung.js (Ablauf für
 * neue Artikel dort im Kopfkommentar).
 *
 * Je veröffentlichtem Slug ein dynamischer Import. Vite legt dadurch jede
 * Inhaltsdatei in einen eigenen Chunk, und eine Artikelseite lädt nur ihren.
 * Nur src/pages/RatgeberArtikelPage.jsx importiert diese Datei.
 */

export const RATGEBER_LOADERS = new Map([
  ['ikk-classic-bonusprogramm-2026', () => import('./ikk-classic-bonusprogramm-2026.js')],
  ['mkk-bonusprogramm-2026', () => import('./mkk-bonusprogramm-2026.js')],
  ['aok-bonusprogramm-2026', () => import('./aok-bonusprogramm-2026.js')],
  ['tk-bonusprogramm-2026', () => import('./tk-bonusprogramm-2026.js')],
  ['barmer-bonusprogramm-2026', () => import('./barmer-bonusprogramm-2026.js')],
  ['schwangerschaft-worauf-achten', () => import('./schwangerschaft-worauf-achten.js')],
  ['krankenkassen-bonus-zusatzversicherung', () => import('./krankenkassen-bonus-zusatzversicherung.js')],
  ['zahnersatz-kosten', () => import('./zahnersatz-kosten.js')],
  ['professionelle-zahnreinigung-kosten', () => import('./professionelle-zahnreinigung-kosten.js')],
  ['zahnimplantat-kosten', () => import('./zahnimplantat-kosten.js')],
  ['wurzelbehandlung-kosten', () => import('./wurzelbehandlung-kosten.js')],
  ['zahnkrone-kosten', () => import('./zahnkrone-kosten.js')],
  ['bonusheft-zahnarzt', () => import('./bonusheft-zahnarzt.js')],
  ['zahnzusatzversicherung-ohne-wartezeit', () => import('./zahnzusatzversicherung-ohne-wartezeit.js')],
  ['zahnzusatzversicherung-fehlender-zahn', () => import('./zahnzusatzversicherung-fehlender-zahn.js')],
  ['zahnzusatzversicherung-lohnt-sich', () => import('./zahnzusatzversicherung-lohnt-sich.js')],
  ['ukv-zahnzusatzversicherung', () => import('./ukv-zahnzusatzversicherung.js')],
  ['bayerische-zahnzusatzversicherung', () => import('./bayerische-zahnzusatzversicherung.js')],
  ['aok-zahnzusatzversicherung', () => import('./aok-zahnzusatzversicherung.js')],
  ['dak-zahnreinigung', () => import('./dak-zahnreinigung.js')],
  ['zahnbruecke-kosten', () => import('./zahnbruecke-kosten.js')],
  ['zahnprothese-kosten', () => import('./zahnprothese-kosten.js')],
  ['zahnfuellung-kosten', () => import('./zahnfuellung-kosten.js')],
  ['parodontitis-behandlung-kosten', () => import('./parodontitis-behandlung-kosten.js')],
  ['zahnersatz-moeglichkeiten', () => import('./zahnersatz-moeglichkeiten.js')],
  ['zahnersatz-haertefall', () => import('./zahnersatz-haertefall.js')],
  ['heilpraktiker-kosten', () => import('./heilpraktiker-kosten.js')],
  ['heilpraktiker-zusatzversicherung', () => import('./heilpraktiker-zusatzversicherung.js')],
  ['ambulante-zusatzversicherung', () => import('./ambulante-zusatzversicherung.js')],
  ['akupunktur-kosten', () => import('./akupunktur-kosten.js')],
  ['tk-osteopathie', () => import('./tk-osteopathie.js')],
  ['chiropraktiker-kosten', () => import('./chiropraktiker-kosten.js')],
  ['physiotherapie-zuzahlung', () => import('./physiotherapie-zuzahlung.js')],
  ['gebuehrenordnung-heilpraktiker', () => import('./gebuehrenordnung-heilpraktiker.js')],
  ['stationaere-zusatzversicherung', () => import('./stationaere-zusatzversicherung.js')],
  ['einzelzimmer-krankenhaus-kosten', () => import('./einzelzimmer-krankenhaus-kosten.js')],
  ['zusatzversicherung-einzelzimmer', () => import('./zusatzversicherung-einzelzimmer.js')],
  ['krankenhaustagegeld', () => import('./krankenhaustagegeld.js')],
  ['reha-zuzahlung', () => import('./reha-zuzahlung.js')],
  ['zusatzversicherung-kinder', () => import('./zusatzversicherung-kinder.js')],
  ['baby-geplant-zusatzversicherung', () => import('./baby-geplant-zusatzversicherung.js')],
  ['neugeborenes-versichern', () => import('./neugeborenes-versichern.js')],
  ['familienzimmer-krankenhaus', () => import('./familienzimmer-krankenhaus.js')],
  ['babybonus-krankenkasse', () => import('./babybonus-krankenkasse.js')],
  ['schwanger-zusatzversicherung', () => import('./schwanger-zusatzversicherung.js')],
  ['schwangerschaft-was-steht-mir-zu', () => import('./schwangerschaft-was-steht-mir-zu.js')],
  ['hebamme-kosten-krankenkasse', () => import('./hebamme-kosten-krankenkasse.js')],
  ['vorsorgeuntersuchung', () => import('./vorsorgeuntersuchung.js')],
  ['vorsorgeuntersuchung-frauen', () => import('./vorsorgeuntersuchung-frauen.js')],
  ['vorsorgeuntersuchung-maenner', () => import('./vorsorgeuntersuchung-maenner.js')],
  ['hautkrebsscreening', () => import('./hautkrebsscreening.js')],
  ['tk-reiseimpfung', () => import('./tk-reiseimpfung.js')],
  ['brille-krankenkasse', () => import('./brille-krankenkasse.js')],
  ['brillenversicherung', () => import('./brillenversicherung.js')],
  ['gleitsichtbrille-kosten', () => import('./gleitsichtbrille-kosten.js')],
]);
