// Zahn-Wege seit Franks Entscheidung vom 05.10.2026: die Bayerische nur für den
// Sofortschutz (Zahntarif plus ZAHN Sofort), alle anderen Situationen UKV
// ZahnPRIVAT. UKV-Fakten geprüft am 05.10.2026 (Antrag FNR342759, Ausgabe
// 06.2026; Tarif Teil II, Stand 01.08.2024; Lückenzähne laut Maklerbetreuer
// nach Zuschlag mitversichert, normale Zahnstaffel, kein eigener Lückendeckel).
// 2-Jahres-Regel zur Behandlungsfrage laut UKV-Maklerbetreuer (05.10.2026): Gab
// es in den letzten 2 Jahren einen Heil- und Kostenplan oder eine Anratung, ist
// genau diese Behandlung ausgeschlossen; liegt das länger zurück, ist sie wieder
// versichert.
// Zeitraum in Frage 1 (Franks Vorgabe 05.10.2026): „empfohlen oder geplant“
// zählt nur in den letzten 2 Jahren (UKV-Antrag 4.2, Annahmerichtlinien der
// Bayerischen 11.2025), „läuft schon“ zählt immer (UKV AVB Teil I § 3 Abs. 1).
// Die positive Aussage „ganz normal mitversichert“ steht nur für die UKV; für
// Kieferorthopädie (UKV-Antrag 4.4) gilt die 2-Jahres-Grenze nicht, darum steht
// die Ausnahme Zahnspange überall dort, wo ältere Empfehlungen als versichert
// gelten, und im Familien-Ergebnis. Schon abgerechnete Behandlungen aus den
// letzten 2 Jahren: Ob UKV-Antrag 4.2 sie erfasst, ist offen (Belege 03.10.,
// beim Versicherer angefragt), darum sagt die Seite dazu nichts.
const de = {
  hero: {
    eyebrow: 'Zahnzusatzversicherung',
    title: 'Dein Lächeln ist dein stärkstes Statussignal. Warum überlässt du es dem Kassenstandard?',
    titleLead: 'Dein Lächeln ist dein stärkstes Statussignal.',
    titleAccent: 'Warum überlässt du es dem Kassenstandard?',
    text: 'Für Zahnersatz und Vorsorge wählst du die Leistung, nicht nur den Preis. Gesundheitsangaben, Zahnstaffel und Tarifbedingungen entscheiden; bereits angeratene oder laufende Behandlungen brauchen einen gesonderten Prüfweg. Dein Kassenbonus kann den Beitrag ganz oder teilweise ausgleichen.',
    cta: 'Zahn-Check starten',
    micro: ['1 Minute', 'ohne Kontaktdaten', 'Annahme erst im Antrag'],
    ticketEyebrow: 'Dein Startpunkt',
    ticketTitle: 'Wurde in den letzten 2 Jahren etwas empfohlen?',
    ticketYes: 'Ja: Sofortschutz prüfen',
    ticketNo: 'Nein: Leistung, Familie oder Preis wählen',
    ticketFooter: '2 Wege. 1 klare Empfehlung.',
    routes: ['UKV ZahnPRIVAT', 'Bayerische mit ZAHN Sofort'],
    iconAlt: 'Freundliches Symbol für Zahnschutz',
    offersAria: 'Zahn-Situationen und ihr Weg im Überblick',
    offers: [
      { code: 'UKV ZahnPRIVAT 100', label: 'Maximaler Zahnschutz', note: '100 % der erstattungsfähigen Kosten nach Kassenleistung, ohne Wartezeit' },
      { code: 'ZAHN Sofort', label: 'Behandlung steht an', note: 'In den letzten 2 Jahren empfohlen oder schon begonnen: bis zu 1.500 EUR Zuschuss möglich, Abschluss vor der Rechnung' },
      { code: 'UKV mit Zuschlag', label: 'Zähne fehlen schon', note: 'Bei 1 bis 3 fehlenden Zähnen Aufnahme mit Zuschlag je Zahn' },
      { code: 'UKV ZahnPRIVAT', label: 'Familie und Vorsorge', note: 'Kieferorthopädie und Zahnreinigung je nach Stufe' },
    ],
    trust: [
      'Registrierter Versicherungsmakler',
      'Antworten bleiben auf dieser Seite',
      'Persönlich erreichbar',
    ],
  },
  check: {
    eyebrow: '1 Minute. Keine Kontaktdaten.',
    title: 'Wo stehst du gerade?',
    titleLead: 'Wo stehst du',
    titleAccent: 'gerade?',
    subtitle: 'Vier kurze Fragen reichen. Danach siehst du den Tarifweg, den du als Nächstes prüfen solltest.',
    stampEyebrow: 'Dein Zahn-Check',
    stampTime: 'ca. 1 Minute',
    stampText: 'Vier Antworten. Ein klarer nächster Schritt.',
    progress: 'Frage {{current}} von höchstens 4',
    back: 'Zurück',
    restart: 'Check neu starten',
    resultEyebrow: 'Dein nächster sinnvoller Schritt',
    warningLabel: 'Darauf kommt es an:',
    trust: 'Deine Antworten werden weder gespeichert noch übertragen.',
    disclaimer: 'Der Check ist eine erste Orientierung. Verbindlich entscheidet der jeweilige Versicherer nach den Angaben im Antrag.',
    bonusLead: 'Dein Bonus kann deinen Tarifbeitrag ganz oder teilweise ausgleichen. Die Höhe hängt von deiner Krankenkasse und deinen Aktivitäten ab.',
    bonusDetail: 'Beitrag, realistisch erreichbarer Bonus und Leistungen stehen getrennt nebeneinander. So findest du die Krankenkasse, die am besten zu deinem Tarif passt.',
    bonusCta: 'Krankenkasse passend zum Tarif finden',
    questions: {
      q1: {
        text: 'Hat dein Zahnarzt in den letzten 2 Jahren eine Behandlung empfohlen oder geplant? Oder läuft sie schon?',
        hint: 'Etwa Krone, Füllung oder Implantat. Geplant heißt: Du hast vom Zahnarzt einen Heil- und Kostenplan bekommen, also einen Kostenvoranschlag.',
        rules: [
          {
            tone: 'mint',
            title: 'Vor mehr als 2 Jahren empfohlen?',
            text: 'Zählt nicht mehr, solange seitdem nichts geplant ist und nichts läuft. Dann wähle Nein. Bei der UKV ist die Behandlung später ganz normal mitversichert. Ausnahme Zahnspange: Da zählt auch eine ältere Empfehlung.',
          },
        ],
        options: {
          ja: { label: 'Ja, etwas steht an oder läuft schon', sub: 'Das zahlt ein normaler Zahntarif nicht, dafür gibt es den Sofortschutz. Auch ein Eintrag in deiner Zahnarzt-Akte aus den letzten 2 Jahren kann zählen.' },
          nein: { label: 'Nein, nichts davon', sub: 'Empfehlungen von vor über 2 Jahren ohne neuen Plan und Kontrollen ohne Befund zählen hier nicht' },
        },
      },
      q2: {
        text: 'Fehlen dir Zähne, die noch nicht ersetzt sind?',
        hint: 'Milch- und Weisheitszähne zählen nicht. Ein vollständiger Lückenschluss zählt ebenfalls nicht als fehlender Zahn.',
        options: {
          keine: { label: 'Nein, alle Zähne sind vorhanden oder ersetzt' },
          wenige: { label: 'Ja, 1 bis 3 Zähne' },
          viele: { label: 'Ja, mehr als 3 Zähne' },
        },
      },
      q3: {
        text: 'Gibt es bei dir eine Zahn-Vorgeschichte, die zu beachten ist?',
        hint: 'Zum Beispiel Parodontitis in den letzten 3 Jahren, eine herausnehmbare Prothese oder Zahnersatz, der älter als 10 Jahre ist.',
        options: {
          ja: { label: 'Ja, mindestens einer dieser Punkte trifft zu' },
          nein: { label: 'Nein, nichts davon' },
        },
      },
      q4: {
        text: 'Was ist dir am wichtigsten?',
        options: {
          leistung: { label: 'Maximale Leistung', sub: 'Starker Schutz für Zahnersatz und Behandlung' },
          familie: { label: 'Familie und Kieferorthopädie', sub: 'Leistungen für Eltern und Kinder' },
          pzr: { label: 'Professionelle Zahnreinigung', sub: 'Regelmäßige Vorsorge im Fokus' },
          preis: { label: 'Günstiger Einstieg', sub: 'Guter Schutz mit kleinerem Beitrag' },
        },
      },
    },
    results: {
      sofort: {
        tone: 'coral',
        insurer: 'die Bayerische · ZAHN Sofort',
        title: 'Sofortschutz vor der Rechnung prüfen',
        text: 'Auch bei einer angeratenen oder begonnenen Behandlung kann noch ein Zuschuss von bis zu 1.500 EUR möglich sein.',
        reasons: [
          'Bis zu 750 EUR je Kalenderjahr, insgesamt bis zu 1.500 EUR',
          'Nur zusammen mit einem neuen Zahntarif der Bayerischen wählbar',
          'Der Baustein endet nach 24 Monaten, der Zahntarif läuft weiter',
        ],
        warning: 'Der Abschluss muss vor der Rechnung erfolgen. Die Behandlung darf noch nicht abgeschlossen oder abgerechnet sein.',
        cta: 'Sofortschutz berechnen',
        ctaType: 'bayerische',
        note: 'Die Annahme und der genaue Leistungsumfang werden verbindlich im Antrag geprüft.',
      },
      ukvLuecke: {
        tone: 'butter',
        insurer: 'UKV · ZahnPRIVAT 75, 90 oder 100',
        title: 'Deine Lücke kann mitversichert werden',
        text: 'Bei 1 bis 3 fehlenden, noch nicht ersetzten Zähnen sieht der UKV-Antrag eine Aufnahme mit Risikozuschlag je Zahn vor. Danach sind die Lückenzähne mitversichert, es gilt die normale Zahnstaffel. Wurde die Versorgung der Lücke in den letzten 2 Jahren angeraten oder geplant, ist genau diese Behandlung nicht versichert.',
        reasons: [
          'Zuschlag je fehlendem Zahn und Monat: 6,10 EUR in Stufe 75, 9,00 EUR in 90, 10,90 EUR in 100',
          'Kein eigener Deckel für die Lücke, keine Wartezeiten',
          'Milch- und Weisheitszähne sowie ein vollständiger Lückenschluss zählen nicht',
        ],
        warning: 'Ab 4 fehlenden Zähnen ist keine Aufnahme möglich. Gab es für deine Lücke in den letzten 2 Jahren einen Heil- und Kostenplan oder wurde ihre Versorgung angeraten, ist genau diese Behandlung nicht versichert. Liegt das länger als 2 Jahre zurück, ist sie wieder versichert.',
        cta: 'UKV-Tarife berechnen',
        ctaType: 'ukv',
        contactLabel: 'Fragen zu deiner Lücke? Sprich vorher mit uns',
        note: 'Du wirst zur ZahnPRIVAT-Abschlussstrecke der UKV weitergeleitet. Gib dort die Anzahl der fehlenden Zähne an.',
      },
      ukvVorgeschichte: {
        tone: 'sky',
        insurer: 'UKV · ZahnPRIVAT',
        title: 'Vorgeschichte sauber im Antrag prüfen',
        text: 'Die UKV kann bei bestimmten Zahn-Vorgeschichten der passendere Prüfweg sein. Welche Stufe passt, hängt von deinen Angaben ab.',
        reasons: [
          'Drei Leistungsstufen für unterschiedliche Budgets',
          'Zahnersatz, Zahnbehandlung und Vorsorge je nach Tarif',
          'Die Gesundheitsfragen entscheiden über die Annahme',
        ],
        warning: 'Nichts beschönigen oder weglassen. Erst der vollständig beantwortete Antrag schafft Klarheit.',
        cta: 'UKV-Tarife berechnen',
        ctaType: 'ukv',
        note: 'Du wirst zur ZahnPRIVAT-Abschlussstrecke der UKV weitergeleitet.',
      },
      ukvFamilie: {
        tone: 'sky',
        insurer: 'UKV · ZahnPRIVAT',
        title: 'Starker Prüfweg für Familien',
        text: 'Wenn Kieferorthopädie und regelmäßige Vorsorge wichtig sind, lohnt sich der Vergleich der ZahnPRIVAT-Stufen.',
        reasons: [
          'Kieferorthopädie-Leistungen je nach gewählter Stufe',
          'Professionelle Zahnreinigung in den Top-Stufen',
          'Leistung und Beitrag lassen sich passend abstufen',
        ],
        warning: 'Wurde für dein Kind schon eine Zahnspange empfohlen, oder läuft sie schon? Dann ist Kieferorthopädie nicht versichert, auch wenn die Empfehlung älter als 2 Jahre ist. Die verbindliche Annahme erfolgt im Antrag.',
        cta: 'UKV-Tarife berechnen',
        ctaType: 'ukv',
        note: 'Du wirst zur ZahnPRIVAT-Abschlussstrecke der UKV weitergeleitet.',
      },
      ukvPzr: {
        tone: 'sky',
        insurer: 'UKV · ZahnPRIVAT',
        title: 'Vorsorge konsequent mitdenken',
        text: 'Wenn professionelle Zahnreinigung bei dir regelmäßig dazugehört, ist ZahnPRIVAT ein sinnvoller Vergleichsweg.',
        reasons: [
          'Professionelle Zahnreinigung je nach Tarifstufe',
          'Zusätzlicher Schutz für Behandlung und Zahnersatz',
          'Drei Stufen für Leistung und Beitrag',
        ],
        warning: 'Leistungsgrenzen und Annahme werden in der gewählten Tarifstufe und im Antrag verbindlich angezeigt.',
        cta: 'UKV-Tarife berechnen',
        ctaType: 'ukv',
        note: 'Du wirst zur ZahnPRIVAT-Abschlussstrecke der UKV weitergeleitet.',
      },
      ukvLeistung: {
        tone: 'mint',
        insurer: 'UKV · ZahnPRIVAT 100',
        title: 'Maximalen Zahnschutz prüfen',
        text: 'Wenn in den letzten 2 Jahren nichts empfohlen wurde, nichts läuft und du hohen Schutz suchst, ist ZahnPRIVAT 100 der klare Leistungsweg.',
        reasons: [
          '100 % der erstattungsfähigen Kosten nach Abzug der Kassenleistung, auch wenn die Kasse nicht vorleistet',
          'Implantate inklusive Knochenaufbau, Brücken und Prothesen erstattungsfähig',
          'Keine Wartezeiten, professionelle Zahnreinigung ohne Jahresdeckel',
        ],
        warning: 'In den ersten drei Kalenderjahren gilt eine Zahnstaffel: bis 1.000 EUR im ersten Jahr, zusammen bis 3.000 EUR in den ersten zwei und bis 6.000 EUR in den ersten drei Jahren, danach endet die Staffel und es gelten allein die Erstattungssätze des Tarifs. Bei Unfall gilt keine Staffel.',
        cta: 'UKV-Tarife berechnen',
        ctaType: 'ukv',
        note: 'Du wirst zur ZahnPRIVAT-Abschlussstrecke der UKV weitergeleitet. Wähle dort ZahnPRIVAT 100.',
      },
      ukvPreis: {
        tone: 'butter',
        insurer: 'UKV · ZahnPRIVAT 75',
        title: 'Leistung und Beitrag bewusst abwägen',
        text: 'Wenn in den letzten 2 Jahren nichts empfohlen wurde, nichts läuft und du einen kleineren Beitrag suchst, ist ZahnPRIVAT 75 die Einstiegsstufe der UKV.',
        reasons: [
          '75 % der erstattungsfähigen Kosten nach Abzug der Kassenleistung, auch wenn die Kasse nicht vorleistet',
          'Keine Wartezeiten, Implantate, Brücken und Prothesen erstattungsfähig',
          'Keine pauschale Preiszusage, dein Beitrag hängt unter anderem vom Alter ab',
        ],
        warning: 'In ZahnPRIVAT 75 gilt eine Zahnstaffel: bis 1.000 EUR im ersten Kalenderjahr, zusammen bis 2.000 EUR in den ersten zwei und bis 3.000 EUR in den ersten drei Jahren, danach endet die Staffel und es gelten allein die Erstattungssätze des Tarifs. Bei Unfall gilt keine Staffel.',
        cta: 'UKV-Tarife berechnen',
        ctaType: 'ukv',
        note: 'Du wirst zur ZahnPRIVAT-Abschlussstrecke der UKV weitergeleitet. Wähle dort ZahnPRIVAT 75 oder vergleiche mit den höheren Stufen.',
      },
      sonderKomplex: {
        tone: 'neutral',
        insurer: 'Persönliche Einordnung durch Healio',
        title: 'Deine Kombination braucht erst einen gemeinsamen Blick',
        text: 'Wenn Behandlung, fehlende Zähne oder Vorgeschichte zusammenkommen, wäre eine automatische Empfehlung zu grob.',
        reasons: [
          'Bestehende Behandlung und künftiger Schutz bleiben getrennt',
          'Du erfährst offen, welche Wege noch prüfbar sind',
          'Du entscheidest erst, wenn die Bedingungen klar sind',
        ],
        warning: 'Eine Annahme oder Leistung lässt sich in dieser Kombination nicht pauschal versprechen.',
        cta: 'Zahn-Situation besprechen',
        ctaType: 'contact',
        note: 'Deine Antworten aus dem Check werden nicht übertragen. Im Gespräch startest du neu.',
      },
      sonderViele: {
        tone: 'neutral',
        insurer: 'Persönliche Einordnung durch Healio',
        title: 'Mehr als 3 fehlende Zähne brauchen einen anderen Weg',
        text: 'Die Standardwege dieser Seite passen dann nicht zuverlässig. Welche Alternativen am Markt noch sinnvoll sein können, prüfst du gemeinsam mit uns.',
        reasons: [
          'Keine automatische Produktempfehlung',
          'Ehrliche Einordnung von Leistung und Grenzen',
          'Erst verstehen, dann entscheiden',
        ],
        warning: 'Wir versprechen keine Annahme. Verbindlich entscheidet immer der Versicherer.',
        cta: 'Zahn-Situation besprechen',
        ctaType: 'contact',
        note: 'Deine Antworten aus dem Check werden nicht übertragen. Im Gespräch startest du neu.',
      },
    },
  },
  paths: {
    eyebrow: 'Zwei Wege. Sauber getrennt.',
    title: 'Deine Zahnsituation entscheidet. Du siehst den Weg, der heute wirklich offen ist.',
    text: 'Der Zahn-Check ordnet zuerst deine Situation ein. Erst danach geht es um Beitrag und Abschluss.',
    cards: [
      {
        key: 'ukv',
        label: 'Leistung, Familie und Zahnlücken',
        title: 'UKV',
        product: 'ZahnPRIVAT 75, 90 oder 100',
        text: 'Für alle, bei denen in den letzten 2 Jahren nichts empfohlen wurde und nichts läuft. Ältere Empfehlungen zählen nicht mehr (außer bei Zahnspangen). Drei Leistungsstufen ohne Wartezeiten. Bei 1 bis 3 fehlenden Zähnen ist die Aufnahme mit Zuschlag je Zahn vorgesehen.',
        tone: 'mint',
      },
      {
        key: 'sofort',
        label: 'Behandlung steht an',
        title: 'die Bayerische',
        product: 'ZAHN Sofort',
        text: 'Für Behandlungen, die in den letzten 2 Jahren empfohlen oder geplant wurden oder schon laufen. Bis zu 1.500 EUR können möglich sein, wenn Abschluss und Rechnung zeitlich richtig liegen. Voraussetzung: Es fehlen keine Zähne und es gibt keine Zahn-Vorgeschichte, zum Beispiel keine Parodontitis in den letzten 3 Jahren und keine herausnehmbare Prothese.',
        tone: 'coral',
      },
    ],
    footer: 'Die Annahme und der genaue Leistungsumfang werden immer erst im Antrag verbindlich geprüft.',
  },
  video: {
    eyebrow: 'Das Konzept in gut einer Minute',
    title: 'So findest du den Zahnschutz, der zu deiner Situation passt.',
    text: 'Das Video zeigt dir, warum eine angeratene Behandlung einen anderen Weg braucht als Vorsorge, Leistungswunsch oder fehlende Zähne.',
    points: [
      'Wann Sofortschutz noch prüfbar sein kann',
      'Wie fehlende Zähne gegen Zuschlag mitversichert werden können',
      'Was erst im Antrag verbindlich entschieden wird',
    ],
    aria: 'Healio Erklärvideo zur Zahnzusatzversicherung',
  },
  bonus: {
    eyebrow: 'KassenBoost nach der Tarifwahl',
    title: 'Finde die Krankenkasse, die am besten zu deinem Tarif passt.',
    text: 'Dein Bonus kann deinen Tarifbeitrag ganz oder teilweise ausgleichen. Die Höhe hängt von deiner Krankenkasse und deinen Aktivitäten ab.',
    detail: 'Beitrag, realistisch erreichbaren Bonus und Leistungen siehst du getrennt, deine persönliche Höhe wird transparent ausgerechnet.',
    cta: 'Zahn-Check starten',
    link: 'Krankenkasse passend zum Tarif finden',
    stamp: 'Laut Satzung bis zu',
    amount: '810 EUR',
    question: 'Wie viel davon holst du raus?',
    stampLabel: 'Höchstwert laut Satzung 2026 · passende Nachweise · anerkannte Eigenkosten',
    condition: 'Alles ausgeschöpft, ohne Schwangerschaft; in der Schwangerschaft bis zu 1.155 EUR. In der breiten Masse sind es 400 bis 700 EUR; der tatsächlich erreichbare Zuschuss hängt von den aktuellen Bonusbedingungen ab.',
  },
  process: {
    eyebrow: 'Einfach erklärt',
    title: 'Erst verstehen. Dann passend absichern.',
    text: 'Du rechnest deinen Tarif online und besprichst offene Punkte am Telefon. Die Entscheidung bleibt bei dir.',
    steps: [
      { title: 'Situation klären', text: 'Der Zahn-Check trennt Behandlung, fehlende Zähne und deinen Leistungswunsch.' },
      { title: 'Tarifweg vergleichen', text: 'Du siehst nur den Weg, der zu deinen Antworten passen kann.' },
      { title: 'Verbindlich prüfen', text: 'Beitrag, Gesundheitsfragen und Annahme siehst du im Antrag des Versicherers.' },
    ],
    trustTitle: 'Nachvollziehbar statt schön gerechnet.',
    trustText: 'Bedingungen stehen in Sichtnähe, und Orientierung, Tarifberechnung und verbindliche Annahme bleiben getrennt.',
    sealNote: 'Auszeichnungen beziehen sich auf die jeweils genannten Tarife und Testjahrgänge.',
  },
  faq: {
    eyebrow: 'Alles Wichtige vor dem Abschluss',
    title: 'Deine Fragen. Klar beantwortet.',
    items: [
      {
        q: 'Es wurde schon eine Behandlung angeraten. Ist es zu spät?',
        a: 'Nicht unbedingt. Es kommt darauf an, wann. Liegt die Empfehlung mehr als 2 Jahre zurück und ist seitdem nichts passiert? Dann ist die Behandlung bei der UKV ganz normal mitversichert. Ausnahme Zahnspange: Da zählt auch eine ältere Empfehlung. Wurde sie in den letzten 2 Jahren empfohlen oder geplant, oder läuft sie schon? Dann zahlt ein normaler Zahntarif sie nicht. Mit ZAHN Sofort können aber bis zu 1.500 EUR Zuschuss möglich sein. Der Abschluss muss vor der Rechnung erfolgen, die Behandlung darf noch nicht abgeschlossen oder abgerechnet sein. Der Baustein ist nur bei einem Neuabschluss wählbar.',
      },
      {
        q: 'Mein Zahnarzt hat vor mehr als 2 Jahren etwas empfohlen. Bin ich trotzdem versichert?',
        a: 'Ja, bei der UKV ZahnPRIVAT. Was dein Zahnarzt vor mehr als 2 Jahren empfohlen oder geplant hat, zählt nicht mehr. Beispiel: Er hat dir im Herbst 2023 eine Krone empfohlen, und du schließt heute ab. Dann ist die Krone ganz normal mitversichert. Es zählt die letzte Empfehlung. Die Behandlung darf außerdem noch nicht laufen oder geplant sein. Anders ist es bei allem, was in den letzten 2 Jahren empfohlen oder geplant wurde: Das zahlt ein normaler Zahntarif nicht, dafür gibt es den Sofortschutz. Ausnahme Zahnspange: Da zählt auch eine ältere Empfehlung. Nach fehlenden Zähnen und Parodontitis fragt der Antrag trotzdem. Verbindlich entscheidet die UKV im Antrag.',
      },
      {
        q: 'Kann ich mich mit fehlenden Zähnen noch versichern?',
        a: 'Ja, bei der UKV ZahnPRIVAT, wenn 1 bis 3 Zähne fehlen und noch nicht ersetzt sind. Je fehlendem Zahn kommt ein monatlicher Risikozuschlag dazu: 6,10 EUR in ZahnPRIVAT 75, 9,00 EUR in 90 und 10,90 EUR in 100. Danach sind die Lückenzähne mitversichert, es gilt die normale Zahnstaffel. Milch- und Weisheitszähne sowie ein vollständiger Lückenschluss zählen nicht. Ab 4 fehlenden Zähnen ist keine Aufnahme möglich. Gab es für die Lücke in den letzten 2 Jahren einen Heil- und Kostenplan oder wurde ihre Versorgung angeraten, ist genau diese Behandlung nicht versichert. Liegt das länger als 2 Jahre zurück, ist sie wieder versichert.',
      },
      {
        q: 'Wie funktioniert der Sofortschutz bei einer laufenden Behandlung?',
        a: 'ZAHN Sofort ist ein Zusatzbaustein zu einem neuen Zahntarif. Bis zu 750 EUR je Kalenderjahr und insgesamt bis zu 1.500 EUR können möglich sein. Der Abschluss muss vor der Rechnung erfolgen; eine bereits abgeschlossene oder abgerechnete Behandlung ist nicht umfasst. Der Baustein endet nach 24 Monaten, der Zahntarif läuft weiter.',
      },
      {
        q: 'Was kostet eine Zahnzusatzversicherung?',
        a: 'Der Beitrag hängt unter anderem von Alter, Tarif und Leistungsstufe ab. Deshalb steht hier kein pauschaler Lockpreis. Im jeweiligen Tarifrechner siehst du deinen konkreten Beitrag, bevor du den Antrag abschickst.',
      },
      {
        q: 'Welche Gesundheitsfragen muss ich beantworten?',
        a: 'Das unterscheidet sich je nach Versicherer und Tarif. Häufig geht es um fehlende Zähne, laufende oder angeratene Behandlungen und bestimmte Vorerkrankungen. Antworte vollständig und wahrheitsgemäß; die exakten Fragen stehen in der jeweiligen Antragsstrecke.',
      },
      {
        q: 'Gibt es Wartezeiten?',
        a: 'Das hängt vom Tarif ab. Auch ohne klassische Wartezeit können Leistungsstaffeln, Höchstgrenzen und Ausschlüsse gelten. Entscheidend sind immer die Tarifbedingungen und der Versicherungsbeginn; bereits bestehende Behandlungen sind dadurch nicht automatisch versichert.',
      },
      {
        q: 'Zahlt mein Kassenbonus den ganzen Beitrag?',
        a: 'Ganz oder teilweise, je nach Krankenkasse und deinen Aktivitäten. Wir rechnen es individuell für dich aus. Beitrag, realistisch erreichbarer Bonus und Leistungen stehen getrennt nebeneinander. So siehst du transparent, welche Krankenkasse am besten zu deinem Tarif passt.',
      },
      {
        q: 'Wie läuft der Abschluss nach dem Zahn-Check ab?',
        a: 'Der Check zeigt dir zunächst den sinnvollen Prüfweg. Danach öffnest du den passenden Tarifrechner, siehst Beitrag und Bedingungen und beantwortest die Gesundheitsfragen. Erst der Versicherer entscheidet im Antrag verbindlich über Annahme und Leistung.',
      },
      {
        q: 'Kann ich den Vertrag später wieder kündigen?',
        a: 'Ja, innerhalb der vertraglichen Regeln. Mindestlaufzeit und Kündigungsfrist können je nach Tarif unterschiedlich sein. Du findest sie vor dem Abschluss in den Versicherungs- und Verbraucherinformationen des Anbieters.',
      },
      {
        q: 'Warum kann ich der Empfehlung von Healio vertrauen?',
        a: 'Healio ist als Versicherungsmakler registriert. Wir trennen Orientierung, Tarifberechnung und verbindliche Annahme, zeigen Bedingungen in Sichtnähe und bleiben bei Fragen persönlich erreichbar. Der Zahn-Check speichert oder überträgt deine Antworten nicht. Verbindlich entscheidet erst der Versicherer im Antrag.',
      },
    ],
    finalEyebrow: 'Dein nächster Schritt',
    finalTitle: 'Finde heraus, welcher Zahnweg zu dir passt.',
    finalText: 'Vier Fragen. Eine klare Richtung. Du entscheidest erst, wenn alles verständlich ist.',
    finalCta: 'Zahn-Check starten',
  },
};

const en = {
  ...de,
  hero: {
    ...de.hero,
    eyebrow: 'Supplementary dental insurance',
    title: 'Your smile is your strongest status signal. Why leave it to statutory standard care?',
    titleLead: 'Your smile is your strongest status signal.',
    titleAccent: 'Why leave it to statutory standard care?',
    text: 'For dentures and prevention, choose the benefits, not just the price. Health declarations, staged benefit limits and policy terms determine cover; recommended or ongoing treatment needs a separate review. Your health fund bonus may offset all or part of the premium.',
    cta: 'Start the dental check',
    micro: ['1 minute', 'no contact details', 'acceptance only in the application'],
    ticketEyebrow: 'Your starting point',
    ticketTitle: 'Has treatment been recommended in the last 2 years?',
    ticketYes: 'Yes: check immediate cover',
    ticketNo: 'No: choose cover, family or price',
    ticketFooter: '2 routes. 1 clear recommendation.',
    routes: ['UKV ZahnPRIVAT', 'die Bayerische with ZAHN Sofort'],
    iconAlt: 'Friendly dental protection icon',
    offersAria: 'Dental situations and their route at a glance',
    offers: [
      { code: 'UKV ZahnPRIVAT 100', label: 'Maximum dental cover', note: '100% of eligible costs after the health fund share, no waiting period' },
      { code: 'ZAHN Sofort', label: 'Treatment coming up', note: 'Recommended in the last 2 years or already started: subsidy of up to €1,500 possible, sign up before the invoice' },
      { code: 'UKV with surcharge', label: 'Teeth already missing', note: 'With 1 to 3 missing teeth, acceptance with a surcharge per tooth' },
      { code: 'UKV ZahnPRIVAT', label: 'Family and prevention', note: 'Orthodontics and teeth cleaning depending on the level' },
    ],
    trust: ['Registered insurance broker', 'Answers stay on this page', 'Personally available'],
  },
  check: {
    ...de.check,
    eyebrow: '1 minute. No contact details.',
    title: 'Where are you right now?',
    titleLead: 'Where are you',
    titleAccent: 'right now?',
    subtitle: 'Four short questions are enough. You will then see the route worth checking next.',
    stampEyebrow: 'Your dental check',
    stampTime: 'about 1 minute',
    stampText: 'Four answers. One clear next step.',
    progress: 'Question {{current}} of up to 4',
    back: 'Back',
    restart: 'Restart check',
    resultEyebrow: 'Your next sensible step',
    warningLabel: 'What matters:',
    trust: 'Your answers are neither stored nor transmitted.',
    disclaimer: 'The check is initial guidance. The insurer makes the binding decision from the information in the application.',
    bonusLead: 'Your bonus can offset all or part of your tariff premium. How much depends on your health fund and your activities.',
    bonusDetail: 'We compare premium, realistically achievable bonus and benefits to find the health fund that best fits your tariff.',
    bonusCta: 'Find the health fund for your tariff',
    questions: {
      q1: {
        text: 'Has your dentist recommended or planned treatment in the last 2 years? Or is it already underway?',
        hint: 'For example a crown, filling or implant. Planned means: your dentist gave you a treatment and cost plan (Heil- und Kostenplan), in other words a cost estimate.',
        rules: [
          {
            tone: 'mint',
            title: 'Recommended more than 2 years ago?',
            text: 'No longer counts as long as nothing has been planned since and nothing is underway. Then choose No. UKV will then cover the treatment as normal. Exception: for braces, an older recommendation still counts.',
          },
        ],
        options: {
          ja: { label: 'Yes, something is due or already underway', sub: 'A normal dental tariff does not pay for that. That is what immediate cover is for. An entry in your dental records from the last 2 years may also count.' },
          nein: { label: 'No, none of these', sub: 'Recommendations from more than 2 years ago without a new plan, and check-ups without findings, do not count here' },
        },
      },
      q2: {
        text: 'Are you missing teeth that have not yet been replaced?',
        hint: 'Baby teeth and wisdom teeth do not count. A complete gap closure does not count either.',
        options: {
          keine: { label: 'No, all teeth are present or replaced' },
          wenige: { label: 'Yes, 1 to 3 teeth' },
          viele: { label: 'Yes, more than 3 teeth' },
        },
      },
      q3: {
        text: 'Is there dental history we should take into account?',
        hint: 'For example periodontitis in the last 3 years, removable dentures or dental prosthetics older than 10 years.',
        options: {
          ja: { label: 'Yes, at least one applies' },
          nein: { label: 'No, none of these' },
        },
      },
      q4: {
        text: 'What matters most to you?',
        options: {
          leistung: { label: 'Maximum benefits', sub: 'Strong cover for treatment and dentures' },
          familie: { label: 'Family and orthodontics', sub: 'Benefits for parents and children' },
          pzr: { label: 'Professional teeth cleaning', sub: 'Regular prevention in focus' },
          preis: { label: 'Affordable entry', sub: 'Good cover with a smaller premium' },
        },
      },
    },
    results: {
      sofort: {
        ...de.check.results.sofort,
        insurer: 'die Bayerische · ZAHN Sofort',
        title: 'Check immediate cover before the invoice',
        text: 'Even when treatment has already been recommended or started, a subsidy of up to €1,500 may still be possible.',
        reasons: [
          'Up to €750 per calendar year and €1,500 in total',
          'Only available together with a new dental tariff from die Bayerische',
          'The module ends after 24 months while the dental tariff continues',
        ],
        warning: 'You must sign up before the invoice. Treatment must not yet be completed or invoiced.',
        cta: 'Calculate immediate cover',
        note: 'Acceptance and exact benefits are checked bindingly in the application.',
      },
      ukvLuecke: {
        ...de.check.results.ukvLuecke,
        insurer: 'UKV · ZahnPRIVAT 75, 90 or 100',
        title: 'Your gap can be covered',
        text: 'With 1 to 3 missing, unreplaced teeth, the UKV application provides for acceptance with a risk surcharge per tooth. The gap teeth are then covered and the normal dental benefit scale applies. If restoring the gap was recommended or planned in the last 2 years, exactly that treatment is not covered.',
        reasons: [
          'Surcharge per missing tooth per month: €6.10 in level 75, €9.00 in 90, €10.90 in 100',
          'No separate cap for the gap, no waiting periods',
          'Baby teeth, wisdom teeth and a complete gap closure do not count',
        ],
        warning: 'With 4 or more missing teeth, acceptance is not possible. If there was a treatment and cost plan for your gap in the last 2 years or its restoration was recommended, exactly that treatment is not covered. If that was more than 2 years ago, it is covered again.',
        cta: 'Calculate UKV tariffs',
        contactLabel: 'Questions about your gap? Talk to us first',
        note: 'You will be redirected to the UKV ZahnPRIVAT application. Enter the number of missing teeth there.',
      },
      ukvVorgeschichte: {
        ...de.check.results.ukvVorgeschichte,
        insurer: 'UKV · ZahnPRIVAT',
        title: 'Check dental history properly in the application',
        text: 'UKV may be the more suitable route for certain dental histories. The right tier depends on your information.',
        reasons: [
          'Three benefit tiers for different budgets',
          'Dentures, treatment and prevention depending on the tariff',
          'The health questions determine acceptance',
        ],
        warning: 'Do not omit or play down anything. Only the fully answered application provides clarity.',
        cta: 'Calculate UKV tariffs',
        note: 'You will be redirected to the UKV ZahnPRIVAT application.',
      },
      ukvFamilie: {
        ...de.check.results.ukvFamilie,
        insurer: 'UKV · ZahnPRIVAT',
        title: 'A strong route to check for families',
        text: 'If orthodontics and regular prevention matter, it is worth comparing the ZahnPRIVAT tiers.',
        reasons: [
          'Orthodontic benefits depending on the selected tier',
          'Professional teeth cleaning in the top tiers',
          'Benefits and premium can be tiered to fit',
        ],
        warning: 'Have braces already been recommended for your child, or are they underway? Then orthodontics is not covered, even if the recommendation is more than 2 years old. Acceptance is binding only in the application.',
        cta: 'Calculate UKV tariffs',
        note: 'You will be redirected to the UKV ZahnPRIVAT application.',
      },
      ukvPzr: {
        ...de.check.results.ukvPzr,
        insurer: 'UKV · ZahnPRIVAT',
        title: 'Include prevention consistently',
        text: 'If professional teeth cleaning is a regular part of your routine, ZahnPRIVAT is a useful comparison route.',
        reasons: [
          'Professional teeth cleaning depending on the tariff tier',
          'Additional cover for treatment and dentures',
          'Three tiers for benefits and premium',
        ],
        warning: 'Benefit limits and acceptance are shown bindingly in the selected tier and application.',
        cta: 'Calculate UKV tariffs',
        note: 'You will be redirected to the UKV ZahnPRIVAT application.',
      },
      ukvLeistung: {
        ...de.check.results.ukvLeistung,
        insurer: 'UKV · ZahnPRIVAT 100',
        title: 'Check maximum dental cover',
        text: 'If nothing has been recommended in the last 2 years, nothing is underway and you want high protection, ZahnPRIVAT 100 is the clear performance route.',
        reasons: [
          '100% of eligible costs after deducting the health fund share, even if the fund pays nothing first',
          'Implants including bone augmentation, bridges and dentures are eligible',
          'No waiting periods, professional teeth cleaning without an annual cap',
        ],
        warning: 'A benefit scale applies in the first three calendar years: up to €1,000 in the first year, up to €3,000 in total over the first two and up to €6,000 over the first three years; after that the scale ends and only the reimbursement rates of the tariff apply. No scale applies after an accident.',
        cta: 'Calculate UKV tariffs',
        note: 'You will be redirected to the UKV ZahnPRIVAT application. Choose ZahnPRIVAT 100 there.',
      },
      ukvPreis: {
        ...de.check.results.ukvPreis,
        insurer: 'UKV · ZahnPRIVAT 75',
        title: 'Balance benefits and premium consciously',
        text: 'If nothing has been recommended in the last 2 years, nothing is underway and you want a smaller premium, ZahnPRIVAT 75 is the UKV entry level.',
        reasons: [
          '75% of eligible costs after deducting the health fund share, even if the fund pays nothing first',
          'No waiting periods, implants, bridges and dentures are eligible',
          'No blanket price promise, your premium depends in part on age',
        ],
        warning: 'ZahnPRIVAT 75 has a benefit scale: up to €1,000 in the first calendar year, up to €2,000 in total over the first two and up to €3,000 over the first three years; after that the scale ends and only the reimbursement rates of the tariff apply. No scale applies after an accident.',
        cta: 'Calculate UKV tariffs',
        note: 'You will be redirected to the UKV ZahnPRIVAT application. Choose ZahnPRIVAT 75 there or compare it with the higher levels.',
      },
      sonderKomplex: {
        ...de.check.results.sonderKomplex,
        insurer: 'Personal guidance from Healio',
        title: 'We should look at this together first',
        text: 'When treatment, missing teeth or dental history overlap, an automated recommendation would be too broad.',
        reasons: [
          'We separate existing treatment from future cover',
          'We explain openly which routes can still be checked',
          'You decide only when the conditions are clear',
        ],
        warning: 'Acceptance or benefits cannot be promised as a blanket statement in this combination.',
        cta: 'Discuss my dental situation',
        note: 'Your check answers are not transmitted. You start fresh in the conversation.',
      },
      sonderViele: {
        ...de.check.results.sonderViele,
        insurer: 'Personal guidance from Healio',
        title: 'More than 3 missing teeth need a different route',
        text: 'The standard routes on this page do not fit reliably. We can check which market alternatives may still make sense.',
        reasons: [
          'No automated product recommendation',
          'Honest explanation of benefits and limits',
          'Understand first, then decide',
        ],
        warning: 'We do not promise acceptance. The insurer always decides bindingly.',
        cta: 'Discuss my dental situation',
        note: 'Your check answers are not transmitted. You start fresh in the conversation.',
      },
    },
  },
  paths: {
    ...de.paths,
    eyebrow: 'Two routes. Clearly separated.',
    title: 'Your dental situation decides. We show you which route is genuinely open today.',
    text: 'The dental check first classifies your situation. Only then do premium and application follow.',
    cards: [
      { ...de.paths.cards[0], label: 'Benefits, family and dental gaps', product: 'ZahnPRIVAT 75, 90 or 100', text: 'For everyone with nothing recommended in the last 2 years and nothing underway. Older recommendations no longer count (except for braces). Three benefit levels without waiting periods. With 1 to 3 missing teeth, acceptance with a surcharge per tooth is provided for.' },
      { ...de.paths.cards[1], label: 'Treatment coming up', text: 'For treatment recommended or planned in the last 2 years, or already underway. Up to €1,500 may be possible when sign-up and invoice timing meet the conditions. Requirement: no missing teeth and no dental history, for example no periodontitis in the last 3 years and no removable dentures.' },
    ],
    footer: 'Acceptance and exact benefits are only checked bindingly in the application.',
  },
  video: {
    eyebrow: 'The concept in just over a minute',
    title: 'How to find dental cover that fits your situation.',
    text: 'The video explains why recommended treatment needs a different route than prevention, benefit priorities or missing teeth.',
    points: [
      'When immediate cover may still be assessable',
      'How missing teeth can be covered for a surcharge',
      'What is only decided bindingly in the application',
    ],
    aria: 'Healio explainer video about supplementary dental insurance',
  },
  bonus: {
    ...de.bonus,
    eyebrow: 'KassenBoost after your tariff choice',
    title: 'Find the health fund that best fits your tariff.',
    text: 'Your bonus can offset all or part of your tariff premium. How much depends on your health fund and your activities.',
    detail: 'We compare premium, realistically achievable bonus and benefits and calculate your personal amount transparently.',
    cta: 'Start the dental check',
    link: 'Find the health fund for your tariff',
    stamp: 'Up to, under the statutes',
    amount: '€810',
    question: 'How much of it can you unlock?',
    stampLabel: 'Maximum under the 2026 statutes · suitable evidence · recognised out-of-pocket costs',
    condition: 'Everything used, without pregnancy; during pregnancy up to €1,155. Most people reach 400 to 700 EUR; the subsidy actually available depends on the current bonus terms.',
  },
  process: {
    ...de.process,
    eyebrow: 'Simply explained',
    title: 'Understand first. Then choose suitable cover.',
    text: 'Healio combines digital tariff routes with personal guidance. You keep the decision.',
    steps: [
      { title: 'Clarify your situation', text: 'The check separates treatment, missing teeth and your benefit priorities.' },
      { title: 'Compare the route', text: 'You only see the route that may match your answers.' },
      { title: 'Check bindingly', text: 'Premium, health questions and acceptance appear in the insurer application.' },
    ],
    trustTitle: 'Transparent, not prettified.',
    trustText: 'We keep conditions visible and separate guidance, tariff calculation and binding acceptance.',
    sealNote: 'Awards relate to the named tariffs and test years.',
  },
  faq: {
    ...de.faq,
    eyebrow: 'Everything important before you apply',
    title: 'Your questions. Clearly answered.',
    items: [
      {
        q: 'Treatment has already been recommended. Is it too late?',
        a: 'Not necessarily. It depends on when. Was it recommended more than 2 years ago and nothing has happened since? Then UKV covers the treatment as normal. Exception: for braces, an older recommendation still counts. Was it recommended or planned in the last 2 years, or is it already underway? Then a normal dental tariff does not pay for it. ZAHN Sofort may still provide a subsidy of up to €1,500. You must sign up before the invoice, treatment must not yet be completed or invoiced, and the module is only available with a new contract.',
      },
      {
        q: 'My dentist recommended something more than 2 years ago. Am I still covered?',
        a: 'Yes, with UKV ZahnPRIVAT. Anything your dentist recommended or planned more than 2 years ago no longer counts. Example: your dentist recommended a crown in autumn 2023 and you sign up today. The crown is then covered as normal. What counts is the most recent recommendation. The treatment must also not be underway or planned yet. Anything recommended or planned in the last 2 years is different: a normal dental tariff does not pay for it, which is what immediate cover is for. Exception: for braces, an older recommendation still counts. The application still asks about missing teeth and periodontitis. UKV makes the binding decision in the application.',
      },
      {
        q: 'Can I still get cover with missing teeth?',
        a: 'Yes, with UKV ZahnPRIVAT if 1 to 3 teeth are missing and not yet replaced. A monthly risk surcharge applies per missing tooth: €6.10 in ZahnPRIVAT 75, €9.00 in 90 and €10.90 in 100. The gap teeth are then covered and the normal dental benefit scale applies. Baby teeth, wisdom teeth and a complete gap closure do not count. With 4 or more missing teeth, acceptance is not possible. If there was a treatment and cost plan (Heil- und Kostenplan) for the gap in the last 2 years or its restoration was recommended, exactly that treatment is not covered. If that was more than 2 years ago, it is covered again.',
      },
      {
        q: 'How does immediate cover work when treatment is underway?',
        a: 'ZAHN Sofort is an add-on to a new dental tariff. Up to €750 per calendar year and €1,500 in total may be possible. You must sign up before the invoice; treatment already completed or invoiced is not included. The add-on ends after 24 months while the dental tariff continues.',
      },
      {
        q: 'What does supplementary dental insurance cost?',
        a: 'The premium depends in part on age, tariff and benefit tier. That is why we do not quote a blanket teaser price. The respective tariff calculator shows your actual premium before you submit the application.',
      },
      {
        q: 'Which health questions do I need to answer?',
        a: 'This varies by insurer and tariff. Questions often cover missing teeth, treatment underway or recommended, and certain pre-existing conditions. Answer fully and truthfully; the exact questions appear in the respective application.',
      },
      {
        q: 'Are there waiting periods?',
        a: 'That depends on the tariff. Even without a traditional waiting period, benefit scales, maximum limits and exclusions may apply. The tariff terms and start date always matter; existing treatment is not automatically insured.',
      },
      {
        q: 'Can my health fund bonus cover the entire premium?',
        a: 'All or part of it, depending on your health fund and your activities. We calculate it individually for you. We compare premium, realistically achievable bonus and benefits so you can see which health fund best fits your tariff.',
      },
      {
        q: 'What happens after the dental check?',
        a: 'The check first shows you the sensible assessment route. You then open the matching tariff calculator, see the premium and conditions and answer the health questions. Only the insurer makes the binding decision on acceptance and benefits.',
      },
      {
        q: 'Can I cancel the contract later?',
        a: 'Yes, within the contractual rules. Minimum term and notice period may differ by tariff. You will find them in the insurer documents before applying.',
      },
      {
        q: 'Why can I trust Healio’s guidance?',
        a: 'Healio is a registered insurance broker. We separate guidance, tariff calculation and binding acceptance, keep conditions visible and remain personally available. The dental check does not store or transmit your answers. Only the insurer makes the binding decision in the application.',
      },
    ],
    finalEyebrow: 'Your next step',
    finalTitle: 'Find the dental route that may suit you.',
    finalText: 'Four questions. One clear direction. You decide only when everything is understandable.',
    finalCta: 'Start the dental check',
  },
};

export const getDentalContent = (lang) => (lang === 'en' ? en : de);
