/**
 * SEO-Konfiguration für alle Routen
 * Wird vom Build-Script verwendet, um individuelle HTML-Dateien mit
 * korrekten Meta-Tags pro Seite zu generieren.
 */

export const seoRoutes = [
  // === DEUTSCH ===
  {
    path: '/',
    title: 'Versicherungen für Privatkunden & Unternehmen | Healio',
    description: 'Private Absicherung und betriebliche Vorsorge verständlich verbinden. Healio begleitet unabhängig, digital und persönlich – von Zusatzschutz bis bAV.',
    canonical: 'https://healio.de',
    keywords: 'Versicherungen Privatkunden, betriebliche Vorsorge, Krankenzusatzversicherung, bAV, bKV, Kassenbonus, Healio',
    lang: 'de',
    hreflang: { de: 'https://healio.de', en: 'https://healio.de/en' },
  },
  {
    path: '/unternehmen',
    title: 'Betriebliches Vorsorgemanagement | bAV, bKV & BGM | Healio',
    description: 'Healio bündelt bAV, bKV, BGM-Koordination und Mitarbeiterkommunikation zu einem betrieblichen Vorsorgesystem – transparent, wirtschaftlich und dauerhaft begleitet.',
    canonical: 'https://healio.de/unternehmen',
    keywords: 'betriebliches Vorsorgemanagement, bAV, bKV, betriebliche Krankenversicherung, BGM Koordination, Benefits Arbeitgeber',
    ogImage: 'https://healio.de/images/healio-hero-markenrelief-v1.webp',
    ogImageWidth: 1586,
    ogImageHeight: 992,
    lang: 'de',
    hreflang: { de: 'https://healio.de/unternehmen', en: 'https://healio.de/en/companies' },
  },
  {
    path: '/ambulant',
    title: 'Ambulante Zusatzversicherung – Bis zu 3.000 € Gesundheitsbudget | Healio',
    description: 'Bis zu 3.000 € Gesundheitsbudget für Heilpraktiker, Osteopathie & Naturheilkunde. Kassenboni + Zusatzversicherung clever kombiniert. Jetzt berechnen!',
    canonical: 'https://healio.de/ambulant',
    keywords: 'ambulante Zusatzversicherung, Gesundheitsbudget, Heilpraktiker Kosten, Osteopathie Erstattung, Naturheilkunde Krankenkasse, Kassenbonus Zusatzversicherung',
    lang: 'de',
    hreflang: { de: 'https://healio.de/ambulant', en: 'https://healio.de/en/outpatient' },
    schemaMarkup: {
      '@context': 'https://schema.org',
      '@graph': [
        {
          '@type': 'Service',
          name: 'Healio Gesundheitsbudget für Heilpraktiker, Osteopathie und Naturheilkunde',
          serviceType: 'Ambulante Zusatzversicherung und Gesundheitsbudget',
          url: 'https://healio.de/ambulant',
          description: 'Bis zu 3.000 € Gesundheitsbudget für Heilpraktiker, Osteopathie und Naturheilkunde durch die Kombination aus Kassenbonus und ambulanter Zusatzversicherung.',
          provider: {
            '@type': 'Organization',
            name: 'Healio GmbH',
            url: 'https://healio.de',
            telephone: '+494089755705',
            email: 'info@healio.de'
          },
          areaServed: {
            '@type': 'Country',
            name: 'Germany'
          },
          offers: {
            '@type': 'Offer',
            availability: 'https://schema.org/InStock',
            priceCurrency: 'EUR',
            description: 'Kostenlose Beratung und Berechnung des möglichen Gesundheitsbudgets'
          }
        },
        {
          '@type': 'FAQPage',
          mainEntity: [
            {
              '@type': 'Question',
              name: 'Gibt es einen Haken? Klingt zu gut um wahr zu sein.',
              acceptedAnswer: {
                '@type': 'Answer',
                text: 'Nein. Das Healio Konzept nutzt bestehende Systeme des deutschen Gesundheitswesens: Kassenboni und passende ambulante Zusatzversicherungen. Voraussetzung ist, dass Versicherte aktiv am Bonusprogramm teilnehmen und die Tarifbedingungen erfüllen.'
              }
            },
            {
              '@type': 'Question',
              name: 'Was kostet eine ambulante Zusatzversicherung monatlich?',
              acceptedAnswer: {
                '@type': 'Answer',
                text: 'Die monatlichen Beiträge liegen je nach Alter und Tarif typischerweise zwischen 15 und 50 Euro. Durch ein starkes Kassenbonusprogramm kann der Bonus die Beiträge in vielen Fällen teilweise oder vollständig ausgleichen.'
              }
            },
            {
              '@type': 'Question',
              name: 'Übernimmt die Krankenkasse Heilpraktiker-Kosten?',
              acceptedAnswer: {
                '@type': 'Answer',
                text: 'Die gesetzliche Krankenversicherung übernimmt Heilpraktiker-Kosten in der Regel nicht. Mit einer passenden ambulanten Zusatzversicherung werden Heilpraktiker-Behandlungen je nach Tarif anteilig bis vollständig erstattet.'
              }
            },
            {
              '@type': 'Question',
              name: 'Werden Osteopathie-Behandlungen erstattet?',
              acceptedAnswer: {
                '@type': 'Answer',
                text: 'Ja. Osteopathie kann über eine passende Zusatzversicherung und je nach Krankenkasse zusätzlich über Kassenleistungen oder Bonusprogramme abgedeckt werden, sofern die jeweiligen Tarif- und Bonusbedingungen erfüllt sind.'
              }
            }
          ]
        }
      ]
    },
  },
  {
    path: '/kassenbonus',
    title: 'Krankenkassenbonus und Beitrag vergleichen | Healio',
    description: 'Krankenkassen nach Beitrag, realistischem Bonus und besonderen Leistungen vergleichen. Erst den persönlichen Vorteil prüfen, dann bewusst entscheiden.',
    canonical: 'https://healio.de/kassenbonus',
    keywords: 'Krankenkassenbonus Vergleich, Krankenkasse wechseln, Zusatzbeitrag vergleichen, Bonusprogramm Krankenkasse, Krankenkassen Leistungen',
    lang: 'de',
    hreflang: { de: 'https://healio.de/kassenbonus', en: 'https://healio.de/en/health-insurance-bonus' },
  },
  {
    path: '/partner',
    title: 'Für Praxen – Gesundheitsbudget verständlich erklären | Healio',
    description: 'Kostenfreie Zusammenarbeit für Heilpraktiker, Osteopathen und Hebammen: Die Praxis informiert, Healio prüft und berät Patienten unabhängig.',
    canonical: 'https://healio.de/partner',
    keywords: 'Healio Partner, Heilpraktiker Partnerprogramm, Patienten Finanzierung Heilpraktiker, Kostenübernahme Naturheilkunde',
    lang: 'de',
    hreflang: { de: 'https://healio.de/partner', en: 'https://healio.de/en/partner' },
  },
  {
    path: '/hebammen',
    title: 'Für Hebammen – Gesundheitsbudget für Familien | Healio',
    description: 'Healio-Partnerprogramm für Hebammen: Familien entlasten, Kurse besser finanzierbar machen und rechtssicher informieren.',
    canonical: 'https://healio.de/hebammen',
    lang: 'de',
    hreflang: { de: 'https://healio.de/hebammen', en: 'https://healio.de/en/midwives' },
  },
  {
    path: '/zahnaerzte',
    title: 'Patientenservice für Zahnarztpraxen | Healio',
    description: 'Neutrale Patienteninformation zu Eigenanteilen, Kassenboni und Zahnschutz. Ohne Tarifberatung, Provision oder Patientendaten durch dein Praxisteam.',
    canonical: 'https://healio.de/zahnaerzte',
    lang: 'de',
  },
  {
    path: '/heilberufe-vorsorge',
    title: 'Heilberufe-Vorsorge für Heilpraktiker und Osteopathen | Healio',
    description: 'Gebündelte Absicherung für Praxis und Leben: Berufshaftpflicht, Praxisausfall, Cyber, Berufsunfähigkeit und Rürup. Exklusive Rahmenkonditionen nur über Healio.',
    canonical: 'https://healio.de/heilberufe-vorsorge',
    lang: 'de',
  },
  {
    path: '/zahn',
    title: 'Zahnzusatzversicherung: Bis zu 100 % Erstattung | Healio',
    description: 'Zahnzusatzversicherung, auch wenn die Behandlung schon angeraten ist: Sofortschutz mit bis zu 1.500 € Zuschuss oder starke Vorsorge mit ZahnPRIVAT. Jetzt passenden Tarif finden!',
    canonical: 'https://healio.de/zahn',
    keywords: 'Zahnzusatzversicherung, Zahnersatz Erstattung, Implantate Versicherung, Zahnversicherung Vergleich',
    lang: 'de',
    hreflang: { de: 'https://healio.de/zahn', en: 'https://healio.de/en/dental' },
  },
  {
    path: '/stationaer',
    title: 'Krankenhauszusatzversicherung: Privatpatient im Krankenhaus | Healio',
    description: 'Krankenhauszusatzversicherung: Einbettzimmer, Chefarztbehandlung, freie Klinikwahl. SDK Klinik-Tarife z. B. ab 6,84 €/Monat (Unfall-Tarif, 30 Jahre). Jetzt berechnen.',
    canonical: 'https://healio.de/stationaer',
    keywords: 'Krankenhauszusatzversicherung, stationäre Zusatzversicherung, Krankenhaus Zusatzversicherung, Chefarztbehandlung, Einbettzimmer Versicherung',
    lang: 'de',
    hreflang: { de: 'https://healio.de/stationaer', en: 'https://healio.de/en/inpatient' },
    schemaMarkup: {
      '@context': 'https://schema.org',
      '@type': 'FAQPage',
      mainEntity: [
        { '@type': 'Question', name: 'Was kostet die Krankenhauszusatzversicherung?', acceptedAnswer: { '@type': 'Answer', text: 'Der Beitrag hängt von Alter und Tarif ab. Beispiele für 30-Jährige: Klinik bei Unfall 6,84 Euro, Klinik 2-Bett 32,82 Euro, Klinik 1-Bett 49,78 Euro im Monat. Mit 46 Jahren: 10,49 / 44,91 / 69,74 Euro. Den persönlichen Beitrag zeigt der Tarifrechner in 2 Minuten.' } },
        { '@type': 'Question', name: 'Was ist der Unterschied zwischen Klinik 1-Bett und Klinik 2-Bett?', acceptedAnswer: { '@type': 'Answer', text: 'Klinik 1-Bett (SP1) bietet die Unterbringung im Ein- oder Zweibettzimmer und 10 Euro Krankenhaustagegeld pro Tag. Klinik 2-Bett (SP2) bietet das Zweibettzimmer und eine Wechseloption in den 1-Bett-Tarif ab dem 30. Geburtstag, alle 5 Jahre bis 65. Beide Tarife enthalten Chefarztbehandlung ohne GOÄ-Begrenzung, freie Krankenhauswahl und Rooming-in.' } },
        { '@type': 'Question', name: 'Was ist der Tarif Klinik bei Unfall?', acceptedAnswer: { '@type': 'Answer', text: 'Der Tarif SPU leistet alle Klinik-Leistungen (Ein- oder Zweibettzimmer, Chefarztbehandlung, freie Klinikwahl), allerdings nur bei unfallbedingten Behandlungen. Dafür ist er besonders günstig: für 30-Jährige 6,84 Euro im Monat. Ideal für Sportler und Aktive.' } },
        { '@type': 'Question', name: 'Gibt es Wartezeiten?', acceptedAnswer: { '@type': 'Answer', text: 'Nein. Die SDK verzichtet in den Klinik-Tarifen auf Wartezeiten, der volle Schutz gilt ab Versicherungsbeginn. Der Vertrag muss allerdings vor der Behandlung stehen, für Versicherungsfälle vor Versicherungsbeginn wird nicht geleistet.' } },
        { '@type': 'Question', name: 'Werden auch privatärztliche Leistungen über dem Höchstsatz erstattet?', acceptedAnswer: { '@type': 'Answer', text: 'Ja. Die Erstattung ist nicht auf die Höchstsätze der Gebührenordnung für Ärzte (GOÄ) begrenzt. Auch darüber hinausgehende Honorare werden erstattet.' } },
        { '@type': 'Question', name: 'Wie hilft der IKK classic Bonus bei der Finanzierung?', acceptedAnswer: { '@type': 'Answer', text: 'Die IKK classic belohnt gesundes Verhalten mit steuerfreien Geldboni und Zuschüssen, zum Beispiel für Vorsorge, Impfungen, Sportverein, Fitness oder das Sportabzeichen. Je nach Aktivitäten kann der Bonus einen großen Teil des Beitrags decken, beim Unfall-Tarif oft sogar den ganzen.' } },
        { '@type': 'Question', name: 'Gilt der Schutz auch für Kinder?', acceptedAnswer: { '@type': 'Answer', text: 'Ja, die Klinik-Tarife gibt es für alle gesetzlich Versicherten, auch für Kinder. Rooming-in gehört zu den Leistungen: Ein Elternteil bleibt beim Kind im Krankenhaus.' } },
        { '@type': 'Question', name: 'Gibt es eine Gesundheitsprüfung?', acceptedAnswer: { '@type': 'Answer', text: 'Ja, wie bei stationären Zusatztarifen üblich gehören Gesundheitsfragen zum Antrag. Der beste Zeitpunkt für den Abschluss ist deshalb, solange man gesund und aktiv ist.' } },
        { '@type': 'Question', name: 'Für wen lohnt sich die Krankenhauszusatzversicherung besonders?', acceptedAnswer: { '@type': 'Answer', text: 'Für alle, die im Ernstfall Wahlfreiheit wollen: Sportler und Aktive (auch über den günstigen Unfall-Tarif), Selbstständige und Familien, die beim Kind bleiben wollen. Voraussetzung ist eine gesetzliche Krankenversicherung.' } }
      ]
    },
  },
  {
    path: '/leistungen',
    title: 'Versicherungen: Ambulant, Zahn, Klinik & Tier | Healio',
    description: 'Wähle den passenden Schutzbereich: ambulant, Zahn, stationär oder Tier. Healio erklärt Leistungen und Grenzen verständlich und unabhängig.',
    canonical: 'https://healio.de/leistungen',
    lang: 'de',
    hreflang: { de: 'https://healio.de/leistungen', en: 'https://healio.de/en/services' },
  },
  {
    path: '/about',
    title: 'Über Healio – Versicherung verständlich begleitet',
    description: 'Die Healio GmbH verbindet unabhängige Versicherungsberatung mit einem Partnernetzwerk für Praxen und Unternehmen – verständlich, persönlich und digital begleitet.',
    canonical: 'https://healio.de/about',
    lang: 'de',
    hreflang: { de: 'https://healio.de/about', en: 'https://healio.de/en/about' },
  },
  {
    path: '/kontakt',
    title: 'Kontakt – Kostenlose Beratung | Healio',
    description: 'Kontaktieren Sie Healio für eine kostenlose Beratung zu Gesundheitsbudget, Zusatzversicherungen und betrieblicher Vorsorge.',
    canonical: 'https://healio.de/kontakt',
    lang: 'de',
    hreflang: { de: 'https://healio.de/kontakt', en: 'https://healio.de/en/contact' },
  },
  {
    path: '/blog',
    title: 'Healio Ratgeber – Gesundheitsbudget, Naturheilkunde & Zusatzversicherung',
    description: 'Expertenwissen zu Gesundheitsbudget, Heilpraktiker-Kosten, IKK Bonus, Naturheilkunde-Erstattung und Zusatzversicherungen.',
    canonical: 'https://healio.de/blog',
    lang: 'de',
    hreflang: { de: 'https://healio.de/blog', en: 'https://healio.de/en/blog' },
  },
  {
    path: '/blog/heilpraktiker-kosten-guide-2026',
    title: 'Heilpraktiker Kosten 2026: Preise, Erstattung & Budget | Healio',
    description: 'Was kostet ein Heilpraktiker 2026? Preise, Beispiele und Wege zur Erstattung durch Zusatzversicherung und Gesundheitsbudget.',
    canonical: 'https://healio.de/blog/heilpraktiker-kosten-guide-2026',
    lang: 'de',
  },
  {
    path: '/blog/heilpraktiker-zusatzversicherung-vergleich-2026',
    title: 'Heilpraktiker Zusatzversicherung Vergleich 2026 | Healio',
    description: 'Heilpraktiker Zusatzversicherung 2026: Welche Leistungen wichtig sind, welche Grenzen es gibt und wie du Erstattung mit Kassenbonus planst.',
    canonical: 'https://healio.de/blog/heilpraktiker-zusatzversicherung-vergleich-2026',
    lang: 'de',
  },
  {
    path: '/blog/ikk-classic-bonus-700-euro',
    title: 'IKK Classic Bonus 700 €+: So nutzt du den Kassenbonus | Healio',
    description: 'So funktioniert der IKK Classic Bonus mit 700 €+ pro Jahr: Aktivitäten, Nachweise und Kombination mit dem Healio Gesundheitsbudget.',
    canonical: 'https://healio.de/blog/ikk-classic-bonus-700-euro',
    lang: 'de',
  },
  {
    path: '/blog/osteopathie-krankenkasse-2026',
    title: 'Osteopathie Krankenkasse 2026: Erstattung & Budget | Healio',
    description: 'Welche Krankenkasse zahlt Osteopathie? Überblick zu Zuschüssen, Grenzen und dem 3.000 € Gesundheitsbudget über Healio.',
    canonical: 'https://healio.de/blog/osteopathie-krankenkasse-2026',
    lang: 'de',
  },
  {
    path: '/blog/naturheilkunde-krankenkasse-2026',
    title: 'Naturheilkunde Krankenkasse 2026: Was wird erstattet? | Healio',
    description: 'Naturheilkunde, Akupunktur, TCM und Heilpraktiker: Was gesetzliche Krankenkassen zahlen und wie ein Gesundheitsbudget hilft.',
    canonical: 'https://healio.de/blog/naturheilkunde-krankenkasse-2026',
    lang: 'de',
  },
  {
    path: '/blog/gesundheitsbudget-3000-euro',
    title: '3.000 € Gesundheitsbudget: Kassenbonus + Zusatzversicherung | Healio',
    description: 'Wie du bis zu 3.000 € Gesundheitsbudget in 2 Jahren nutzt: Kassenbonus, Zusatzversicherung und Erstattung für Naturheilkunde.',
    canonical: 'https://healio.de/blog/gesundheitsbudget-3000-euro',
    lang: 'de',
  },
  {
    path: '/potenzialanalyse',
    title: 'Kostenlose Potenzialanalyse – Betriebliche Vorsorge | Healio B2B',
    description: 'Potenzialanalyse für betriebliche Altersvorsorge (bAV) und Krankenversicherung (bKV). Individuelle Berechnung für Ihr Unternehmen.',
    canonical: 'https://healio.de/potenzialanalyse',
    lang: 'de',
    hreflang: { de: 'https://healio.de/potenzialanalyse', en: 'https://healio.de/en/potential-analysis' },
  },
  {
    path: '/terminvereinbarung',
    title: 'Termin vereinbaren – Kostenlose Beratung | Healio',
    description: 'Vereinbaren Sie jetzt einen kostenlosen Beratungstermin bei Healio. Persönliche Beratung zu Gesundheitsbudget und Zusatzversicherungen.',
    canonical: 'https://healio.de/terminvereinbarung',
    lang: 'de',
    hreflang: { de: 'https://healio.de/terminvereinbarung', en: 'https://healio.de/en/appointment' },
  },
  {
    path: '/confirmation',
    title: 'Bestätigung | Healio',
    description: 'Vielen Dank für Ihre Anfrage bei Healio.',
    canonical: 'https://healio.de/confirmation',
    lang: 'de',
    robots: 'noindex, nofollow',
  },
  {
    path: '/tierkrankenversicherung',
    title: 'Tierkrankenversicherung – Schutz für Hund & Katze | Healio',
    description: 'Tierkrankenversicherung für Hund und Katze: OP-Schutz, Krankenvollversicherung, schnelle Erstattung. Jetzt Tarife vergleichen.',
    canonical: 'https://healio.de/tierkrankenversicherung',
    lang: 'de',
    hreflang: { de: 'https://healio.de/tierkrankenversicherung', en: 'https://healio.de/en/pet-insurance' },
  },
  {
    path: '/impressum',
    title: 'Impressum | Healio GmbH',
    description: 'Impressum der Healio GmbH, Hamburg. Anbieterangaben gemäß § 5 DDG.',
    canonical: 'https://healio.de/impressum',
    lang: 'de',
    hreflang: { de: 'https://healio.de/impressum', en: 'https://healio.de/en/legal-notice' },
  },
  {
    path: '/agb',
    title: 'AGB – Allgemeine Geschäftsbedingungen | Healio',
    description: 'Allgemeine Geschäftsbedingungen der Healio GmbH.',
    canonical: 'https://healio.de/agb',
    lang: 'de',
    hreflang: { de: 'https://healio.de/agb', en: 'https://healio.de/en/terms' },
  },
  {
    path: '/datenschutz',
    title: 'Datenschutzerklärung | Healio GmbH',
    description: 'Datenschutzerklärung der Healio GmbH. Informationen zum Umgang mit personenbezogenen Daten.',
    canonical: 'https://healio.de/datenschutz',
    lang: 'de',
    hreflang: { de: 'https://healio.de/datenschutz', en: 'https://healio.de/en/privacy' },
  },
  {
    path: '/erstinformation',
    title: 'Erstinformation für Versicherungsnehmer | Healio',
    description: 'Erstinformation der Healio GmbH gemäß §§ 15 und 16 VersVermV mit Vermittlerstatus, Vergütung, Registerangaben, Schlichtungsstellen und Beratungsgrundlage nach § 60 VVG.',
    canonical: 'https://healio.de/erstinformation',
    lang: 'de',
    hreflang: { de: 'https://healio.de/erstinformation', en: 'https://healio.de/en/initial-information' },
  },

  // === BLOG-ARTIKEL (Heilpraktiker-Zielgruppe) ===
  {
    path: '/blog/heilpraktiker-patienten-finanzierung-gesundheitsbudget',
    title: 'Heilpraktiker Kostenübernahme: 3.000 € Budget | Healio',
    description: 'Patienten brechen Heilpraktiker-Behandlungen oft aus Kostengründen ab. Das Healio Gesundheitsbudget ermöglicht bis zu 3.000 € in 2 Jahren.',
    canonical: 'https://healio.de/blog/heilpraktiker-patienten-finanzierung-gesundheitsbudget',
    lang: 'de',
  },
  {
    path: '/blog/digitale-erstattung-heilpraktiker-rechnungen-zusatzversicherung',
    title: 'Heilpraktiker Abrechnung vereinfachen: Digitale Erstattung App | Healio',
    description: 'Digitale Erstattung per App reduziert Rechnungsdiskussionen. Healio verbindet Zusatzversicherung und Kassenbonus zum 3.000 € Gesundheitsbudget.',
    canonical: 'https://healio.de/blog/digitale-erstattung-heilpraktiker-rechnungen-zusatzversicherung',
    lang: 'de',
  },
  {
    path: '/blog/heilpraktiker-kosten-gkv-erstattung-healio',
    title: 'Heilpraktiker-Kosten GKV: Warum alles selbst zahlen + Lösung | Healio',
    description: 'GKV zahlt Heilpraktiker-Kosten meist nicht. Erfahre, wie Healio Kassenbonus und Zusatzversicherung zu bis zu 3.000 € Budget kombiniert.',
    canonical: 'https://healio.de/blog/heilpraktiker-kosten-gkv-erstattung-healio',
    lang: 'de',
  },
  {
    path: '/blog/zahnzusatzversicherung-trotz-angeratener-behandlung',
    title: 'Zahnzusatzversicherung trotz angeratener Behandlung: Sofortschutz | Healio',
    description: 'Behandlung schon angeraten? Der Baustein ZAHN Sofort der Bayerischen zahlt bis zu 1.500 € Zuschuss, wenn der Abschluss vor der Rechnung erfolgt.',
    canonical: 'https://healio.de/blog/zahnzusatzversicherung-trotz-angeratener-behandlung',
    lang: 'de',
  },
  {
    path: '/blog/krankenhauszusatzversicherung-sportverein-best-ager',
    title: 'Krankenhauszusatzversicherung ab 50: Sportverein zahlt sich doppelt aus | Healio',
    description: 'Fit im Sportverein? Dann bekommst du den Klinik-Tarif leichter und der IKK Bonus kann den Beitrag bis zu 100 % refinanzieren.',
    canonical: 'https://healio.de/blog/krankenhauszusatzversicherung-sportverein-best-ager',
    lang: 'de',
  },
  {
    path: '/blog/healio-konzept-fuer-heilpraktiker',
    title: 'Das Healio-Konzept für Heilpraktiker | Healio',
    description: 'Therapieabbrüche wegen Geld? Das Healio-Konzept gibt deinen Patienten bis zu 3.000 € Gesundheitsbudget für Naturheilkunde.',
    canonical: 'https://healio.de/blog/healio-konzept-fuer-heilpraktiker',
    lang: 'de',
  },
  {
    path: '/blog/healio-konzept-fuer-osteopathen',
    title: 'Das Healio-Konzept für Osteopathen | Healio',
    description: 'Kassen streichen Osteopathie-Zuschüsse. Das Healio-Konzept gibt deinen Patienten bis zu 3.000 € Budget, IKK-Bonus inklusive.',
    canonical: 'https://healio.de/blog/healio-konzept-fuer-osteopathen',
    lang: 'de',
  },
  {
    path: '/blog/healio-konzept-fuer-tcm-praxen',
    title: 'Das Healio-Konzept für TCM-Praxen | Healio',
    description: 'GKV zahlt Akupunktur nur in Ausnahmen. Das Healio-Konzept gibt deinen Patienten bis zu 3.000 € Budget für TCM beim Heilpraktiker.',
    canonical: 'https://healio.de/blog/healio-konzept-fuer-tcm-praxen',
    lang: 'de',
  },
  {
    path: '/blog/healio-konzept-fuer-hebammen',
    title: 'Das Healio-Konzept für Hebammen | Healio',
    description: 'Werdende Eltern vertrauen deiner Empfehlung. Das Healio-Konzept bringt Familien bis zu 3.000 € Gesundheitsbudget plus Vorsorge-Topf.',
    canonical: 'https://healio.de/blog/healio-konzept-fuer-hebammen',
    lang: 'de',
  },

  // === ENGLISCH ===
  {
    path: '/en',
    title: 'Supplementary health insurance, made simple | Healio',
    description: 'Compare outpatient, dental and hospital supplementary insurance with clarity. Healio supports you digitally and personally, from selection to ongoing service.',
    canonical: 'https://healio.de/en',
    lang: 'en',
    hreflang: { de: 'https://healio.de', en: 'https://healio.de/en' },
  },
  {
    path: '/en/companies',
    title: 'Corporate Benefits Management | Pension, Health & Wellbeing | Healio',
    description: 'Healio combines corporate pension, health insurance, wellbeing coordination and employee communication into one managed benefits system.',
    canonical: 'https://healio.de/en/companies',
    ogImage: 'https://healio.de/images/healio-hero-markenrelief-v1.webp',
    ogImageWidth: 1586,
    ogImageHeight: 992,
    lang: 'en',
    hreflang: { de: 'https://healio.de/unternehmen', en: 'https://healio.de/en/companies' },
  },
  {
    path: '/en/outpatient',
    title: 'Outpatient Supplementary Insurance – Up to 3,000 € Health Budget | Healio',
    description: 'Up to 3,000 € health budget for naturopathy, osteopathy & alternative medicine. Smart combination of health insurance bonuses.',
    canonical: 'https://healio.de/en/outpatient',
    lang: 'en',
    hreflang: { de: 'https://healio.de/ambulant', en: 'https://healio.de/en/outpatient' },
  },
  {
    path: '/en/health-insurance-bonus',
    title: 'Compare German Health Insurance Bonuses and Costs | Healio',
    description: 'Compare German statutory health insurers by contribution, realistic bonus and relevant extra benefits before making a decision.',
    canonical: 'https://healio.de/en/health-insurance-bonus',
    keywords: 'German health insurance comparison, statutory health insurance bonus, Krankenkasse contribution, health insurance benefits Germany',
    lang: 'en',
    hreflang: { de: 'https://healio.de/kassenbonus', en: 'https://healio.de/en/health-insurance-bonus' },
  },
  {
    path: '/en/partner',
    title: 'For Practices – Explain Health Budgets Clearly | Healio',
    description: 'A free partnership for naturopaths, osteopaths and midwives: The practice provides information while Healio independently reviews and advises patients.',
    canonical: 'https://healio.de/en/partner',
    lang: 'en',
    hreflang: { de: 'https://healio.de/partner', en: 'https://healio.de/en/partner' },
  },
  {
    path: '/en/dental',
    title: 'Dental Insurance – Up to 100% Coverage | Healio',
    description: 'Dental supplementary insurance with up to 100% coverage for dental prosthetics, prophylaxis and orthodontics.',
    canonical: 'https://healio.de/en/dental',
    lang: 'en',
    hreflang: { de: 'https://healio.de/zahn', en: 'https://healio.de/en/dental' },
  },
  {
    path: '/en/inpatient',
    title: 'Hospital Supplementary Insurance: Private Patient in Hospital | Healio',
    description: 'Hospital supplementary insurance: private room, chief physician treatment, free hospital choice. SDK hospital plans, e.g. from 6.84 €/month (accident plan, age 30).',
    canonical: 'https://healio.de/en/inpatient',
    lang: 'en',
    hreflang: { de: 'https://healio.de/stationaer', en: 'https://healio.de/en/inpatient' },
  },
  {
    path: '/en/services',
    title: 'Insurance: Outpatient, Dental, Hospital & Pet | Healio',
    description: 'Choose the right area of cover: outpatient, dental, hospital or pet. Healio explains benefits and limits clearly and independently.',
    canonical: 'https://healio.de/en/services',
    lang: 'en',
    hreflang: { de: 'https://healio.de/leistungen', en: 'https://healio.de/en/services' },
  },
  {
    path: '/en/about',
    title: 'About Healio – Insurance, Clearly Guided',
    description: 'Healio GmbH combines independent insurance advice with a partner network for practices and companies – clear, personal and digitally supported.',
    canonical: 'https://healio.de/en/about',
    lang: 'en',
    hreflang: { de: 'https://healio.de/about', en: 'https://healio.de/en/about' },
  },
  {
    path: '/en/contact',
    title: 'Contact – Free Consultation | Healio',
    description: 'Contact Healio for a free consultation on health budgets, supplementary insurance and corporate benefits.',
    canonical: 'https://healio.de/en/contact',
    lang: 'en',
    hreflang: { de: 'https://healio.de/kontakt', en: 'https://healio.de/en/contact' },
  },
  {
    path: '/en/initial-information',
    title: 'Initial information for insurance customers | Healio',
    description: 'Initial information from Healio GmbH pursuant to §§ 15 and 16 VersVermV, including intermediary status, remuneration, register details, dispute resolution bodies and the basis of advice under section 60 VVG.',
    canonical: 'https://healio.de/en/initial-information',
    lang: 'en',
    hreflang: { de: 'https://healio.de/erstinformation', en: 'https://healio.de/en/initial-information' },
  },
  {
    path: '/en/blog',
    title: 'Healio Guide – Health Budget, Naturopathy & Insurance',
    description: 'Expert knowledge on health budgets, practitioner costs, insurance bonuses and supplementary coverage.',
    canonical: 'https://healio.de/en/blog',
    lang: 'en',
    hreflang: { de: 'https://healio.de/blog', en: 'https://healio.de/en/blog' },
  },
  {
    path: '/en/midwives',
    title: 'For Midwives – Health Budget for Families | Healio',
    description: 'Healio partner programme for midwives: relieve families financially, make courses easier to afford and inform parents on a legally safe basis.',
    canonical: 'https://healio.de/en/midwives',
    lang: 'en',
    hreflang: { de: 'https://healio.de/hebammen', en: 'https://healio.de/en/midwives' },
  },
  {
    path: '/en/appointment',
    title: 'Book an Appointment – Free Consultation | Healio',
    description: 'Book a free consultation with Healio. Personal advice on health budgets and supplementary health insurance.',
    canonical: 'https://healio.de/en/appointment',
    lang: 'en',
    hreflang: { de: 'https://healio.de/terminvereinbarung', en: 'https://healio.de/en/appointment' },
  },
  {
    path: '/en/potential-analysis',
    title: 'Free Potential Analysis – Corporate Benefits | Healio',
    description: 'Potential analysis for corporate pension (bAV) and corporate health insurance (bKV). Individual calculation for your company.',
    canonical: 'https://healio.de/en/potential-analysis',
    lang: 'en',
    hreflang: { de: 'https://healio.de/potenzialanalyse', en: 'https://healio.de/en/potential-analysis' },
  },
  {
    path: '/en/pet-insurance',
    title: 'Pet Health Insurance – Cover for Dogs & Cats | Healio',
    description: 'Pet health insurance for dogs and cats: surgery cover, full health cover and fast reimbursement. Compare plans now.',
    canonical: 'https://healio.de/en/pet-insurance',
    lang: 'en',
    hreflang: { de: 'https://healio.de/tierkrankenversicherung', en: 'https://healio.de/en/pet-insurance' },
  },
  {
    path: '/en/legal-notice',
    title: 'Legal Notice | Healio GmbH',
    description: 'Legal notice of Healio GmbH, Hamburg. Provider information pursuant to section 5 DDG.',
    canonical: 'https://healio.de/en/legal-notice',
    lang: 'en',
    hreflang: { de: 'https://healio.de/impressum', en: 'https://healio.de/en/legal-notice' },
  },
  {
    path: '/en/terms',
    title: 'Terms and Conditions | Healio',
    description: 'General terms and conditions of Healio GmbH.',
    canonical: 'https://healio.de/en/terms',
    lang: 'en',
    hreflang: { de: 'https://healio.de/agb', en: 'https://healio.de/en/terms' },
  },
  {
    path: '/en/privacy',
    title: 'Privacy Policy | Healio GmbH',
    description: 'Privacy policy of Healio GmbH. Information on how personal data is processed.',
    canonical: 'https://healio.de/en/privacy',
    lang: 'en',
    hreflang: { de: 'https://healio.de/datenschutz', en: 'https://healio.de/en/privacy' },
  },

  // === FUNKTIONS- UND KAMPAGNENSEITEN (nicht für den Index bestimmt) ===
  // Diese Routen existieren im Router, sollen aber nicht in die Google-Suche.
  // Ohne eigenen Eintrag liefert der Vercel-Catch-all sonst die Startseite
  // samt Startseiten-Canonical aus -> Search Console meldet
  // "Alternative Seite mit richtigem kanonischen Tag".
  {
    path: '/lebenshilfe',
    title: 'Betriebliche Vorsorge für die Lebenshilfe | Healio',
    description: 'Informationsseite zur betrieblichen Vorsorge für die Lebenshilfe.',
    canonical: 'https://healio.de/lebenshilfe',
    lang: 'de',
    robots: 'noindex, nofollow',
  },
  {
    path: '/zahnaerzte/praxis-checkliste',
    title: 'Praxis-Checkliste für Zahnarztpraxen | Healio',
    description: 'B2B-Arbeitsunterlage mit fünf Konzeptgrenzen für sachliche Patienteninformation in Zahnarztpraxen.',
    canonical: 'https://healio.de/zahnaerzte/praxis-checkliste',
    lang: 'de',
    robots: 'noindex, nofollow',
  },
  {
    path: '/konto-loeschen',
    title: 'Konto löschen | Healio',
    description: 'Löschung des Healio-App-Kontos beantragen.',
    canonical: 'https://healio.de/konto-loeschen',
    lang: 'de',
    robots: 'noindex, follow',
  },
  {
    path: '/app-bestaetigt',
    title: 'E-Mail-Adresse bestätigt | Healio',
    description: 'Die E-Mail-Adresse für die Healio App wurde bestätigt.',
    canonical: 'https://healio.de/app-bestaetigt',
    lang: 'de',
    robots: 'noindex, nofollow',
  },
  {
    path: '/reset-password',
    title: 'Passwort zurücksetzen | Healio',
    description: 'Passwort für die Healio App zurücksetzen.',
    canonical: 'https://healio.de/reset-password',
    lang: 'de',
    robots: 'noindex, nofollow',
  },
  {
    path: '/en/confirmation',
    title: 'Confirmation | Healio',
    description: 'Thank you for your enquiry to Healio.',
    canonical: 'https://healio.de/en/confirmation',
    lang: 'en',
    robots: 'noindex, nofollow',
  },
  {
    path: '/tiktok',
    title: 'Healio auf TikTok | Healio',
    description: 'Alle Healio-Links aus der TikTok-Bio auf einen Blick.',
    canonical: 'https://healio.de/tiktok',
    lang: 'de',
    robots: 'noindex, follow',
  },
  {
    path: '/en/tiktok',
    title: 'Healio on TikTok | Healio',
    description: 'All Healio links from the TikTok bio at a glance.',
    canonical: 'https://healio.de/en/tiktok',
    lang: 'en',
    robots: 'noindex, follow',
  },
  {
    path: '/instagram',
    title: 'Healio auf Instagram | Healio',
    description: 'Alle Healio-Links aus der Instagram-Bio auf einen Blick.',
    canonical: 'https://healio.de/instagram',
    lang: 'de',
    robots: 'noindex, follow',
  },
  {
    path: '/en/instagram',
    title: 'Healio on Instagram | Healio',
    description: 'All Healio links from the Instagram bio at a glance.',
    canonical: 'https://healio.de/en/instagram',
    lang: 'en',
    robots: 'noindex, follow',
  },
];
