/**
 * SEO-Konfiguration für alle Routen
 * Wird vom Build-Script verwendet, um individuelle HTML-Dateien mit
 * korrekten Meta-Tags pro Seite zu generieren.
 */

export const seoRoutes = [
  // === DEUTSCH ===
  {
    path: '/',
    title: 'Healio B2B – Betriebliche Vorsorge neu gedacht | bAV & bKV Experten Hamburg',
    description: 'HEALIO – Ihr Experte für betriebliche Altersvorsorge (bAV) und betriebliche Krankenversicherung (bKV) in Hamburg. Individuelle Beratung für Unternehmen.',
    canonical: 'https://www.healio.de',
    lang: 'de',
    hreflang: { de: 'https://www.healio.de', en: 'https://www.healio.de/en' },
  },
  {
    path: '/ambulant',
    title: 'Ambulante Zusatzversicherung – Bis zu 3.000 € Gesundheitsbudget | Healio',
    description: 'Bis zu 3.000 € Gesundheitsbudget für Heilpraktiker, Osteopathie & Naturheilkunde. Kassenboni + Zusatzversicherung clever kombiniert. Jetzt berechnen!',
    canonical: 'https://www.healio.de/ambulant',
    lang: 'de',
    hreflang: { de: 'https://www.healio.de/ambulant', en: 'https://www.healio.de/en/outpatient' },
  },
  {
    path: '/heilpraktiker-zusatzversicherung',
    title: 'Heilpraktiker Zusatzversicherung – 3.000 € Budget | Vergleich 2026 | Healio',
    description: 'Heilpraktiker Zusatzversicherung im Vergleich 2026: Bis zu 3.000 € Gesundheitsbudget durch IKK Bonus + SDK Zusatzversicherung. Ohne Wartezeit starten.',
    canonical: 'https://www.healio.de/heilpraktiker-zusatzversicherung',
    lang: 'de',
  },
  {
    path: '/partner',
    title: 'Für Heilpraktiker – Mehr Patienten durch Kostenübernahme | Healio',
    description: 'Healio-Partnerprogramm für Heilpraktiker: Therapieabbrüche verhindern, Patientenbindung stärken, Umsatz steigern. Kostenlose Partnerschaft.',
    canonical: 'https://www.healio.de/partner',
    lang: 'de',
    hreflang: { de: 'https://www.healio.de/partner', en: 'https://www.healio.de/en/partner' },
  },
  {
    path: '/zahn',
    title: 'Zahnzusatzversicherung – Bis zu 100 % Erstattung | Healio',
    description: 'Zahnzusatzversicherung mit bis zu 100 % Erstattung für Zahnersatz, Prophylaxe und KFO. Ab 8,55 € im Monat. Jetzt Beitrag berechnen!',
    canonical: 'https://www.healio.de/zahn',
    lang: 'de',
    hreflang: { de: 'https://www.healio.de/zahn', en: 'https://www.healio.de/en/dental' },
  },
  {
    path: '/stationaer',
    title: 'Stationäre Zusatzversicherung – Privatpatient im Krankenhaus | Healio',
    description: 'Stationäre Zusatzversicherung: Einzelzimmer, Chefarztbehandlung, freie Krankenhauswahl. Privatpatienten-Status als Kassenpatient.',
    canonical: 'https://www.healio.de/stationaer',
    lang: 'de',
    hreflang: { de: 'https://www.healio.de/stationaer', en: 'https://www.healio.de/en/inpatient' },
  },
  {
    path: '/leistungen',
    title: 'Unsere Leistungen – Gesundheitsbudget & Zusatzversicherungen | Healio',
    description: 'Alle Healio-Leistungen im Überblick: Ambulante Zusatzversicherung, Zahnzusatz, stationäre Absicherung und betriebliche Vorsorge.',
    canonical: 'https://www.healio.de/leistungen',
    lang: 'de',
    hreflang: { de: 'https://www.healio.de/leistungen', en: 'https://www.healio.de/en/services' },
  },
  {
    path: '/about',
    title: 'Über Healio – Ganzheitliche Gesundheit neu gedacht | Healio',
    description: 'Healio verbindet Kassenboni mit Zusatzversicherungen zu einem Gesundheitsbudget von bis zu 3.000 €. Für Patienten und Heilpraktiker.',
    canonical: 'https://www.healio.de/about',
    lang: 'de',
    hreflang: { de: 'https://www.healio.de/about', en: 'https://www.healio.de/en/about' },
  },
  {
    path: '/kontakt',
    title: 'Kontakt – Kostenlose Beratung | Healio',
    description: 'Kontaktieren Sie Healio für eine kostenlose Beratung zu Gesundheitsbudget, Zusatzversicherungen und betrieblicher Vorsorge.',
    canonical: 'https://www.healio.de/kontakt',
    lang: 'de',
    hreflang: { de: 'https://www.healio.de/kontakt', en: 'https://www.healio.de/en/contact' },
  },
  {
    path: '/blog',
    title: 'Healio Ratgeber – Gesundheitsbudget, Naturheilkunde & Zusatzversicherung',
    description: 'Expertenwissen zu Gesundheitsbudget, Heilpraktiker-Kosten, IKK Bonus, Naturheilkunde-Erstattung und Zusatzversicherungen.',
    canonical: 'https://www.healio.de/blog',
    lang: 'de',
    hreflang: { de: 'https://www.healio.de/blog', en: 'https://www.healio.de/en/blog' },
  },
  {
    path: '/potenzialanalyse',
    title: 'Kostenlose Potenzialanalyse – Betriebliche Vorsorge | Healio B2B',
    description: 'Potenzialanalyse für betriebliche Altersvorsorge (bAV) und Krankenversicherung (bKV). Individuelle Berechnung für Ihr Unternehmen.',
    canonical: 'https://www.healio.de/potenzialanalyse',
    lang: 'de',
  },
  {
    path: '/klinik-upgrade',
    title: 'Klinik-Upgrade – Privatpatient im Krankenhaus | Healio',
    description: 'Klinik-Upgrade: Chefarzt, Einzelzimmer und freie Krankenhauswahl als Kassenpatient. Jetzt Privatpatienten-Komfort sichern.',
    canonical: 'https://www.healio.de/klinik-upgrade',
    lang: 'de',
  },
  {
    path: '/healio-zahnzusatz',
    title: 'Healio Zahnzusatz – Premium Zahnversicherung | Healio',
    description: 'Premium Zahnzusatzversicherung von Healio: Bis zu 100 % Erstattung für Zahnersatz, Implantate, Prophylaxe und Kieferorthopädie.',
    canonical: 'https://www.healio.de/healio-zahnzusatz',
    lang: 'de',
  },
  {
    path: '/terminvereinbarung',
    title: 'Termin vereinbaren – Kostenlose Beratung | Healio',
    description: 'Vereinbaren Sie jetzt einen kostenlosen Beratungstermin bei Healio. Persönliche Beratung zu Gesundheitsbudget und Zusatzversicherungen.',
    canonical: 'https://www.healio.de/terminvereinbarung',
    lang: 'de',
  },
  {
    path: '/tierkrankenversicherung',
    title: 'Tierkrankenversicherung – Schutz für Hund & Katze | Healio',
    description: 'Tierkrankenversicherung für Hund und Katze: OP-Schutz, Krankenvollversicherung, schnelle Erstattung. Jetzt Tarife vergleichen.',
    canonical: 'https://www.healio.de/tierkrankenversicherung',
    lang: 'de',
  },
  {
    path: '/impressum',
    title: 'Impressum | Healio GmbH',
    description: 'Impressum der Healio GmbH, Hamburg. Angaben gemäß § 5 TMG.',
    canonical: 'https://www.healio.de/impressum',
    lang: 'de',
  },
  {
    path: '/agb',
    title: 'AGB – Allgemeine Geschäftsbedingungen | Healio',
    description: 'Allgemeine Geschäftsbedingungen der Healio GmbH.',
    canonical: 'https://www.healio.de/agb',
    lang: 'de',
  },
  {
    path: '/datenschutz',
    title: 'Datenschutzerklärung | Healio GmbH',
    description: 'Datenschutzerklärung der Healio GmbH. Informationen zum Umgang mit personenbezogenen Daten.',
    canonical: 'https://www.healio.de/datenschutz',
    lang: 'de',
  },

  // === ENGLISCH ===
  {
    path: '/en',
    title: 'Healio B2B – Corporate Benefits Reimagined | Hamburg',
    description: 'HEALIO – Your expert for company pension schemes and corporate health insurance in Hamburg. Tailored consulting for businesses.',
    canonical: 'https://www.healio.de/en',
    lang: 'en',
    hreflang: { de: 'https://www.healio.de', en: 'https://www.healio.de/en' },
  },
  {
    path: '/en/outpatient',
    title: 'Outpatient Supplementary Insurance – Up to 3,000 € Health Budget | Healio',
    description: 'Up to 3,000 € health budget for naturopathy, osteopathy & alternative medicine. Smart combination of health insurance bonuses.',
    canonical: 'https://www.healio.de/en/outpatient',
    lang: 'en',
    hreflang: { de: 'https://www.healio.de/ambulant', en: 'https://www.healio.de/en/outpatient' },
  },
  {
    path: '/en/partner',
    title: 'For Practitioners – More Patients Through Cost Coverage | Healio',
    description: 'Healio partner program for practitioners: Prevent therapy dropouts, strengthen patient loyalty, increase revenue.',
    canonical: 'https://www.healio.de/en/partner',
    lang: 'en',
    hreflang: { de: 'https://www.healio.de/partner', en: 'https://www.healio.de/en/partner' },
  },
  {
    path: '/en/dental',
    title: 'Dental Insurance – Up to 100% Coverage | Healio',
    description: 'Dental supplementary insurance with up to 100% coverage for dental prosthetics, prophylaxis and orthodontics.',
    canonical: 'https://www.healio.de/en/dental',
    lang: 'en',
    hreflang: { de: 'https://www.healio.de/zahn', en: 'https://www.healio.de/en/dental' },
  },
  {
    path: '/en/inpatient',
    title: 'Hospital Insurance – Private Patient Status | Healio',
    description: 'Hospital supplementary insurance: Private room, chief physician treatment, free hospital choice.',
    canonical: 'https://www.healio.de/en/inpatient',
    lang: 'en',
    hreflang: { de: 'https://www.healio.de/stationaer', en: 'https://www.healio.de/en/inpatient' },
  },
  {
    path: '/en/services',
    title: 'Our Services – Health Budget & Supplementary Insurance | Healio',
    description: 'All Healio services at a glance: Outpatient insurance, dental, hospital coverage and corporate benefits.',
    canonical: 'https://www.healio.de/en/services',
    lang: 'en',
    hreflang: { de: 'https://www.healio.de/leistungen', en: 'https://www.healio.de/en/services' },
  },
  {
    path: '/en/about',
    title: 'About Healio – Holistic Health Reimagined | Healio',
    description: 'Healio combines insurance bonuses with supplementary coverage for a health budget of up to 3,000 €.',
    canonical: 'https://www.healio.de/en/about',
    lang: 'en',
    hreflang: { de: 'https://www.healio.de/about', en: 'https://www.healio.de/en/about' },
  },
  {
    path: '/en/contact',
    title: 'Contact – Free Consultation | Healio',
    description: 'Contact Healio for a free consultation on health budgets, supplementary insurance and corporate benefits.',
    canonical: 'https://www.healio.de/en/contact',
    lang: 'en',
    hreflang: { de: 'https://www.healio.de/kontakt', en: 'https://www.healio.de/en/contact' },
  },
  {
    path: '/en/blog',
    title: 'Healio Guide – Health Budget, Naturopathy & Insurance',
    description: 'Expert knowledge on health budgets, practitioner costs, insurance bonuses and supplementary coverage.',
    canonical: 'https://www.healio.de/en/blog',
    lang: 'en',
    hreflang: { de: 'https://www.healio.de/blog', en: 'https://www.healio.de/en/blog' },
  },
];
