/**
 * SEO-Konfiguration für alle Routen
 * Wird vom Build-Script verwendet, um individuelle HTML-Dateien mit
 * korrekten Meta-Tags pro Seite zu generieren.
 */

export const seoRoutes = [
  // === DEUTSCH ===
  {
    path: '/',
    title: 'Versicherungen für Privatkunden & Unternehmen | Healio',
    description: 'Private Absicherung und betriebliche Vorsorge verständlich verbinden. Healio begleitet unabhängig, digital und persönlich – von Zusatzschutz bis bAV.',
    canonical: 'https://healio.de',
    keywords: 'Versicherungen Privatkunden, betriebliche Vorsorge, Krankenzusatzversicherung, bAV, bKV, Kassenbonus, Healio',
    lang: 'de',
    hreflang: { de: 'https://healio.de', en: 'https://healio.de/en' },
  },
  {
    path: '/unternehmen',
    title: 'Betriebliches Vorsorgemanagement | bAV, bKV & BGM | Healio',
    description: 'Healio bündelt bAV, bKV, BGM-Koordination und Mitarbeiterkommunikation zu einem betrieblichen Vorsorgesystem – transparent, wirtschaftlich und dauerhaft begleitet.',
    canonical: 'https://healio.de/unternehmen',
    keywords: 'betriebliches Vorsorgemanagement, bAV, bKV, betriebliche Krankenversicherung, BGM Koordination, Benefits Arbeitgeber',
    ogImage: 'https://healio.de/images/healio-hero-markenrelief-v1.webp',
    ogImageWidth: 1586,
    ogImageHeight: 992,
    lang: 'de',
    hreflang: { de: 'https://healio.de/unternehmen', en: 'https://healio.de/en/companies' },
  },
  {
    path: '/kassenboost',
    title: 'Kassenbonus nutzen: Von KassenBoost zu Healio',
    description: 'Du hast bei KassenBoost verglichen? Healio zeigt dir, wie du deinen Kassenbonus als Geld auszahlen lässt oder verdreifacht in Zusatzschutz übersetzt. Kostenlos, unabhängig, ohne Datenübergabe.',
    canonical: 'https://healio.de/kassenboost',
    keywords: 'Krankenkassenvergleich, gesetzliche Krankenkasse vergleichen, KassenBoost, Healio, privater Krankenkassenvergleich',
    ogImage: 'https://healio.de/images/kassenboost-bridge-og.png',
    ogImageAlt: 'KassenBoost und Healio: vergleichen, Bonus nutzen, absichern',
    ogImageWidth: 1200,
    ogImageHeight: 630,
    lang: 'de',
    hreflang: { de: 'https://healio.de/kassenboost', en: 'https://healio.de/en/kassenboost' },
    schemaMarkup: {
      '@context': 'https://schema.org',
      '@type': 'WebPage',
      '@id': 'https://healio.de/kassenboost#webpage',
      url: 'https://healio.de/kassenboost',
      name: 'KassenBoost & Healio: Krankenkasse privat vergleichen',
      description: 'Vergleiche gesetzliche Krankenkassen privat bei KassenBoost. Danach entscheidest du selbst, ob Zusatzschutz oder ein Arbeitgeberangebot von Healio für dich relevant ist.',
      inLanguage: 'de-DE',
      isPartOf: { '@id': 'https://healio.de/#website' },
      about: { '@id': 'https://healio.de/#organization' },
    },
  },
  {
    path: '/kassenbonus',
    title: 'Krankenkassenbonus und Beitrag vergleichen | Healio',
    description: 'Krankenkassen nach Beitrag, realistischem Bonus und besonderen Leistungen vergleichen. Erst den persönlichen Vorteil prüfen, dann bewusst entscheiden.',
    canonical: 'https://healio.de/kassenbonus',
    keywords: 'Krankenkassenbonus Vergleich, Krankenkasse wechseln, Zusatzbeitrag vergleichen, Bonusprogramm Krankenkasse, Krankenkassen Leistungen',
    lang: 'de',
    hreflang: { de: 'https://healio.de/kassenbonus', en: 'https://healio.de/en/health-insurance-bonus' },
  },
  {
    path: '/schwangerschaft',
    title: 'Schwangerschaft: Bonus und Zusatzschutz prüfen | Healio',
    description: 'Welche Vorsorge zählt für deinen Bonus? Prüfe dein persönliches Beispiel und unterscheide Kassenbonus, Beitrag und Zusatzschutz. Ohne Wechsel- oder Terminpflicht.',
    canonical: 'https://healio.de/schwangerschaft',
    keywords: 'Schwangerschaft Kassenbonus, Schwangerschaft Vorsorge Bonus, Zusatzversicherung Schwangerschaft, Healio',
    lang: 'de',
    schemaMarkup: {
      '@context': 'https://schema.org',
      '@type': 'WebPage',
      '@id': 'https://healio.de/schwangerschaft#webpage',
      url: 'https://healio.de/schwangerschaft',
      name: 'Schwangerschaft: Bonus und Zusatzschutz prüfen',
      description: 'Individuelles Bonusbeispiel und verständliche Einordnung von Kassenbonus, Beitrag und tariflichen Leistungen. Kein pauschales Erstattungsversprechen.',
      inLanguage: 'de-DE',
      isPartOf: { '@id': 'https://healio.de/#website' },
      about: { '@id': 'https://healio.de/#organization' },
    },
  },
  {
    path: '/ambulant',
    title: 'Ambulante Zusatzversicherung – Bis zu 3.000 € Gesundheitsbudget | Healio',
    description: 'Bis zu 3.000 € Gesundheitsbudget für Heilpraktiker, Osteopathie & Naturheilkunde. Kassenboni + Zusatzversicherung clever kombiniert. Jetzt berechnen!',
    canonical: 'https://healio.de/ambulant',
    keywords: 'ambulante Zusatzversicherung, Gesundheitsbudget, Heilpraktiker Kosten, Osteopathie Erstattung, Naturheilkunde Krankenkasse, Kassenbonus Zusatzversicherung',
    lang: 'de',
    hreflang: { de: 'https://healio.de/ambulant', en: 'https://healio.de/en/outpatient' },
    schemaMarkup: {
      '@context': 'https://schema.org',
      '@graph': [
        {
          '@type': 'Service',
          name: 'Healio Gesundheitsbudget für Heilpraktiker, Osteopathie und Naturheilkunde',
          serviceType: 'Ambulante Zusatzversicherung und Gesundheitsbudget',
          url: 'https://healio.de/ambulant',
          description: 'Bis zu 3.000 € Gesundheitsbudget für Heilpraktiker, Osteopathie und Naturheilkunde durch die Kombination aus Kassenbonus und ambulanter Zusatzversicherung.',
          provider: {
            '@type': 'Organization',
            name: 'Healio GmbH',
            url: 'https://healio.de',
            telephone: '+494089755705',
            email: 'info@healio.de'
          },
          areaServed: {
            '@type': 'Country',
            name: 'Germany'
          },
          offers: {
            '@type': 'Offer',
            availability: 'https://schema.org/InStock',
            priceCurrency: 'EUR',
            description: 'Kostenlose Beratung und Berechnung des möglichen Gesundheitsbudgets'
          }
        },
        {
          '@type': 'FAQPage',
          mainEntity: [
            {
              '@type': 'Question',
              name: 'Gibt es einen Haken? Klingt zu gut um wahr zu sein.',
              acceptedAnswer: {
                '@type': 'Answer',
                text: 'Nein. Das Healio Konzept nutzt bestehende Systeme des deutschen Gesundheitswesens: Kassenboni und passende ambulante Zusatzversicherungen. Voraussetzung ist, dass Versicherte aktiv am Bonusprogramm teilnehmen und die Tarifbedingungen erfüllen.'
              }
            },
            {
              '@type': 'Question',
              name: 'Was kostet eine ambulante Zusatzversicherung monatlich?',
              acceptedAnswer: {
                '@type': 'Answer',
                text: 'Die monatlichen Beiträge liegen je nach Alter und Tarif typischerweise zwischen 15 und 50 Euro. Durch ein starkes Kassenbonusprogramm kann der Bonus die Beiträge in vielen Fällen teilweise oder vollständig ausgleichen.'
              }
            },
            {
              '@type': 'Question',
              name: 'Übernimmt die Krankenkasse Heilpraktiker-Kosten?',
              acceptedAnswer: {
                '@type': 'Answer',
                text: 'Die gesetzliche Krankenversicherung übernimmt Heilpraktiker-Kosten in der Regel nicht. Mit einer passenden ambulanten Zusatzversicherung werden Heilpraktiker-Behandlungen je nach Tarif anteilig bis vollständig erstattet.'
              }
            },
            {
              '@type': 'Question',
              name: 'Werden Osteopathie-Behandlungen erstattet?',
              acceptedAnswer: {
                '@type': 'Answer',
                text: 'Ja. Osteopathie kann über eine passende Zusatzversicherung und je nach Krankenkasse zusätzlich über Kassenleistungen oder Bonusprogramme abgedeckt werden, sofern die jeweiligen Tarif- und Bonusbedingungen erfüllt sind.'
              }
            }
          ]
        }
      ]
    },
  },
  {
    path: '/partner',
    title: 'Für Praxen – Gesundheitsbudget verständlich erklären | Healio',
    description: 'Kostenfreie Zusammenarbeit für Heilpraktiker, Osteopathen und Hebammen: Die Praxis informiert, Healio prüft und berät Patienten unabhängig.',
    canonical: 'https://healio.de/partner',
    keywords: 'Healio Partner, Heilpraktiker Partnerprogramm, Patienten Finanzierung Heilpraktiker, Kostenübernahme Naturheilkunde',
    lang: 'de',
    hreflang: { de: 'https://healio.de/partner', en: 'https://healio.de/en/partner' },
    schemaMarkup: {
      '@context': 'https://schema.org',
      '@type': 'FAQPage',
      mainEntity: [
        { '@type': 'Question', name: 'Was genau ist das Healio Gesundheitsbudget?', acceptedAnswer: { '@type': 'Answer', text: 'Je nach persönlicher Situation können Patienten mögliche Kassenboni mit tariflichen Leistungen einer Zusatzversicherung kombinieren. So sind bis zu 3.000 EUR Gesundheitsbudget in zwei Jahren möglich. Healio prüft im Einzelfall, welche Voraussetzungen erfüllt sind.' } },
        { '@type': 'Question', name: 'Kostet mich die Partnerschaft etwas?', acceptedAnswer: { '@type': 'Answer', text: 'Für die Partnerpraxis fällt keine Teilnahmegebühr an. Informationsmaterialien und Aufsteller stellt Healio kostenfrei zur Verfügung. Nach dem Kennenlernen entscheidest du selbst, ob und wo du die Informationen einsetzen möchtest.' } },
        { '@type': 'Question', name: 'Muss ich Versicherungen erklären oder empfehlen?', acceptedAnswer: { '@type': 'Answer', text: 'Nein. Deine Aufgabe ist ausschließlich die neutrale Information. Die individuelle Prüfung, Versicherungsberatung, Vermittlung und Antragsbegleitung übernimmt Healio direkt mit dem interessierten Patienten.' } },
        { '@type': 'Question', name: 'Welche Leistungen können erstattet werden?', acceptedAnswer: { '@type': 'Answer', text: 'Je nach Tarif können unter anderem Naturheilkunde, Osteopathie, TCM, Chiropraktik, Sehhilfen und Zahnleistungen berücksichtigt werden. Umfang, Wartezeiten und Erstattungsvoraussetzungen richten sich immer nach dem gewählten Tarif.' } },
        { '@type': 'Question', name: 'Muss ich mein Praxiskonzept ändern?', acceptedAnswer: { '@type': 'Answer', text: 'Nein. Behandlung, Preisgestaltung und fachliche Entscheidungen bleiben vollständig bei dir. Healio ergänzt lediglich einen neutralen Informationsweg für Patienten, die ihre Finanzierungsmöglichkeiten prüfen möchten.' } },
        { '@type': 'Question', name: 'Wie setzen sich die Leistungen für Sehhilfen zusammen?', acceptedAnswer: { '@type': 'Answer', text: 'Die SDK sieht tariflich bis zu 500 EUR für Sehhilfen vor. Separat kann durch nachgewiesene Maßnahmen ein frei verwendbarer IKK-Geldbonus entstehen, der den Eigenanteil zusätzlich reduzieren kann. Er ist kein pauschaler Brillenzuschuss.' } }
      ]
    },
  },
  {
    path: '/hebammen',
    title: 'Für Hebammen – Gesundheitsbudget für Familien | Healio',
    description: 'Healio-Partnerprogramm für Hebammen: Familien entlasten, Kurse besser finanzierbar machen und rechtssicher informieren.',
    canonical: 'https://healio.de/hebammen',
    lang: 'de',
    hreflang: { de: 'https://healio.de/hebammen', en: 'https://healio.de/en/midwives' },
  },
  {
    path: '/zahnaerzte',
    title: 'Patientenservice für Zahnarztpraxen | Healio',
    description: 'Neutrale Patienteninformation zu Eigenanteilen, Kassenboni und Zahnschutz. Ohne Tarifberatung, Provision oder Patientendaten durch dein Praxisteam.',
    canonical: 'https://healio.de/zahnaerzte',
    lang: 'de',
  },
  {
    path: '/heilberufe-vorsorge',
    title: 'Heilberufe-Vorsorge für Heilpraktiker und Osteopathen | Healio',
    description: 'Gebündelte Absicherung für Praxis und Leben: Berufshaftpflicht, Praxisausfall, Cyber, Berufsunfähigkeit und Rürup. Exklusive Rahmenkonditionen nur über Healio.',
    canonical: 'https://healio.de/heilberufe-vorsorge',
    lang: 'de',
    hreflang: { de: 'https://healio.de/heilberufe-vorsorge', en: 'https://healio.de/en/healthcare-professionals-protection' },
  },
  {
    path: '/zahn',
    title: 'Zahnzusatzversicherung: Bis zu 100 % Erstattung | Healio',
    description: 'Zahnzusatzversicherung, auch wenn die Behandlung schon angeraten ist: Sofortschutz mit bis zu 1.500 € Zuschuss oder starke Vorsorge mit ZahnPRIVAT. Jetzt passenden Tarif finden!',
    canonical: 'https://healio.de/zahn',
    keywords: 'Zahnzusatzversicherung, Zahnersatz Erstattung, Implantate Versicherung, Zahnversicherung Vergleich',
    lang: 'de',
    hreflang: { de: 'https://healio.de/zahn', en: 'https://healio.de/en/dental' },
    schemaMarkup: {
      '@context': 'https://schema.org',
      '@type': 'FAQPage',
      mainEntity: [
        { '@type': 'Question', name: 'Es wurde schon eine Behandlung angeraten. Ist es zu spät?', acceptedAnswer: { '@type': 'Answer', text: 'Nicht unbedingt. Mit ZAHN Sofort können bis zu 1.500 EUR Zuschuss möglich sein. Der Abschluss muss vor der Rechnung erfolgen, die Behandlung darf noch nicht abgeschlossen oder abgerechnet sein. Der Baustein ist nur bei einem Neuabschluss wählbar.' } },
        { '@type': 'Question', name: 'Kann ich mich mit fehlenden Zähnen noch versichern?', acceptedAnswer: { '@type': 'Answer', text: 'Bei der LKH ist ZahnUpgrade 70+ oder 90+ mit bis zu 3 fehlenden, noch nicht ersetzten Zähnen grundsätzlich prüfbar. Laut Annahmerichtlinie gelten 5 EUR Zuschlag je fehlendem Zahn. Bereits angeratene, beabsichtigte oder begonnene Behandlungen sind ausgeschlossen. Verbindlich entscheidet der Antrag.' } },
        { '@type': 'Question', name: 'Wie funktioniert der Sofortschutz bei einer laufenden Behandlung?', acceptedAnswer: { '@type': 'Answer', text: 'ZAHN Sofort ist ein Zusatzbaustein zu einem neuen Zahntarif. Bis zu 750 EUR je Kalenderjahr und insgesamt bis zu 1.500 EUR können möglich sein. Der Abschluss muss vor der Rechnung erfolgen; eine bereits abgeschlossene oder abgerechnete Behandlung ist nicht umfasst. Der Baustein endet nach 24 Monaten, der Zahntarif läuft weiter.' } },
        { '@type': 'Question', name: 'Was kostet eine Zahnzusatzversicherung?', acceptedAnswer: { '@type': 'Answer', text: 'Der Beitrag hängt unter anderem von Alter, Tarif und Leistungsstufe ab. Deshalb nennen wir keinen pauschalen Lockpreis. Im jeweiligen Tarifrechner siehst du deinen konkreten Beitrag, bevor du den Antrag abschickst.' } },
        { '@type': 'Question', name: 'Welche Gesundheitsfragen muss ich beantworten?', acceptedAnswer: { '@type': 'Answer', text: 'Das unterscheidet sich je nach Versicherer und Tarif. Häufig geht es um fehlende Zähne, laufende oder angeratene Behandlungen und bestimmte Vorerkrankungen. Antworte vollständig und wahrheitsgemäß; die exakten Fragen stehen in der jeweiligen Antragsstrecke.' } },
        { '@type': 'Question', name: 'Gibt es Wartezeiten?', acceptedAnswer: { '@type': 'Answer', text: 'Das hängt vom Tarif ab. Auch ohne klassische Wartezeit können Leistungsstaffeln, Höchstgrenzen und Ausschlüsse gelten. Entscheidend sind immer die Tarifbedingungen und der Versicherungsbeginn; bereits bestehende Behandlungen sind dadurch nicht automatisch versichert.' } },
        { '@type': 'Question', name: 'Zahlt mein Kassenbonus den ganzen Beitrag?', acceptedAnswer: { '@type': 'Answer', text: 'Dein Bonus kann deinen effektiven Tarifbeitrag bis zu 100 % ausgleichen. Wir vergleichen Beitrag, realistisch erreichbaren Bonus und Leistungen. So siehst du transparent, welche Krankenkasse am besten zu deinem Tarif passt.' } },
        { '@type': 'Question', name: 'Wie läuft der Abschluss nach dem Zahn-Check ab?', acceptedAnswer: { '@type': 'Answer', text: 'Der Check zeigt dir zunächst den sinnvollen Prüfweg. Danach öffnest du den passenden Tarifrechner, siehst Beitrag und Bedingungen und beantwortest die Gesundheitsfragen. Erst der Versicherer entscheidet im Antrag verbindlich über Annahme und Leistung.' } },
        { '@type': 'Question', name: 'Kann ich den Vertrag später wieder kündigen?', acceptedAnswer: { '@type': 'Answer', text: 'Ja, innerhalb der vertraglichen Regeln. Mindestlaufzeit und Kündigungsfrist können je nach Tarif unterschiedlich sein. Du findest sie vor dem Abschluss in den Versicherungs- und Verbraucherinformationen des Anbieters.' } },
        { '@type': 'Question', name: 'Warum kann ich der Empfehlung von Healio vertrauen?', acceptedAnswer: { '@type': 'Answer', text: 'Healio ist als Versicherungsmakler registriert. Wir trennen Orientierung, Tarifberechnung und verbindliche Annahme, zeigen Bedingungen in Sichtnähe und bleiben bei Fragen persönlich erreichbar. Der Zahn-Check speichert oder überträgt deine Antworten nicht. Verbindlich entscheidet erst der Versicherer im Antrag.' } }
      ]
    },
  },
  {
    path: '/stationaer',
    title: 'Krankenhauszusatzversicherung: Privatpatient im Krankenhaus | Healio',
    description: 'Krankenhauszusatzversicherung: Einbettzimmer, Chefarztbehandlung, freie Klinikwahl. SDK Klinik-Tarife z. B. ab 7,00 EUR/Monat (SPU, 30 Jahre). Jetzt berechnen.',
    canonical: 'https://healio.de/stationaer',
    keywords: 'Krankenhauszusatzversicherung, stationäre Zusatzversicherung, Krankenhaus Zusatzversicherung, Chefarztbehandlung, Einbettzimmer Versicherung',
    lang: 'de',
    hreflang: { de: 'https://healio.de/stationaer', en: 'https://healio.de/en/inpatient' },
    schemaMarkup: {
      '@context': 'https://schema.org',
      '@type': 'FAQPage',
      mainEntity: [
        { '@type': 'Question', name: 'Was kostet die Krankenhauszusatzversicherung?', acceptedAnswer: { '@type': 'Answer', text: 'Der Beitrag hängt von Alter und Tarif ab. Aktuelle Beispiele für 30-Jährige: Klinik bei Unfall (SPU) 7,00 EUR, Klinik 2-Bett (SP2) 33,41 EUR und Klinik 1-Bett (SP1) 50,72 EUR im Monat. Den persönlichen Beitrag zeigt der Tarifrechner in 2 Minuten.' } },
        { '@type': 'Question', name: 'Was ist der Unterschied zwischen Klinik 1-Bett und Klinik 2-Bett?', acceptedAnswer: { '@type': 'Answer', text: 'Klinik 1-Bett (SP1) bietet die Unterbringung im Ein- oder Zweibettzimmer und 10 Euro Krankenhaustagegeld pro Tag. Klinik 2-Bett (SP2) bietet das Zweibettzimmer und eine Wechseloption in den 1-Bett-Tarif ab dem 30. Geburtstag, alle 5 Jahre bis 65. Beide Tarife enthalten Chefarztbehandlung ohne GOÄ-Begrenzung, freie Krankenhauswahl und Rooming-in.' } },
        { '@type': 'Question', name: 'Was ist der Tarif Klinik bei Unfall?', acceptedAnswer: { '@type': 'Answer', text: 'Der Tarif SPU leistet alle Klinik-Leistungen (Ein- oder Zweibettzimmer, Chefarztbehandlung, freie Klinikwahl), allerdings nur bei unfallbedingten Behandlungen. Dafür ist er besonders günstig: für 30-Jährige 7,00 EUR im Monat. Ideal für Sportler und Aktive.' } },
        { '@type': 'Question', name: 'Gibt es Wartezeiten?', acceptedAnswer: { '@type': 'Answer', text: 'Nein. Die SDK verzichtet in den Klinik-Tarifen auf Wartezeiten, der volle Schutz gilt ab Versicherungsbeginn. Der Vertrag muss allerdings vor der Behandlung stehen, für Versicherungsfälle vor Versicherungsbeginn wird nicht geleistet.' } },
        { '@type': 'Question', name: 'Werden auch privatärztliche Leistungen über dem Höchstsatz erstattet?', acceptedAnswer: { '@type': 'Answer', text: 'Ja. Die Erstattung ist nicht auf die Höchstsätze der Gebührenordnung für Ärzte (GOÄ) begrenzt. Auch darüber hinausgehende Honorare werden erstattet.' } },
        { '@type': 'Question', name: 'Wie hilft der IKK classic Bonus bei der Finanzierung?', acceptedAnswer: { '@type': 'Answer', text: 'Die IKK classic belohnt anerkannte Aktivitäten wahlweise mit einem Geldbonus oder einem dreifach höheren Zuschuss für nachgewiesene zuschussfähige Kosten. Je nach Aktivitäten und anrechenbaren Kosten kann der Zuschuss einen großen Teil des Beitrags decken, beim Unfall-Tarif sogar bis zu 100 Prozent.' } },
        { '@type': 'Question', name: 'Gilt der Schutz auch für Kinder?', acceptedAnswer: { '@type': 'Answer', text: 'Ja, die Klinik-Tarife gibt es für alle gesetzlich Versicherten, auch für Kinder. Rooming-in gehört zu den Leistungen: Ein Elternteil bleibt beim Kind im Krankenhaus.' } },
        { '@type': 'Question', name: 'Gibt es eine Gesundheitsprüfung?', acceptedAnswer: { '@type': 'Answer', text: 'Ja, wie bei stationären Zusatztarifen üblich gehören Gesundheitsfragen zum Antrag. Der beste Zeitpunkt für den Abschluss ist deshalb, solange man gesund und aktiv ist.' } },
        { '@type': 'Question', name: 'Für wen lohnt sich die Krankenhauszusatzversicherung besonders?', acceptedAnswer: { '@type': 'Answer', text: 'Für alle, die im Ernstfall Wahlfreiheit wollen: Sportler und Aktive (auch über den günstigen Unfall-Tarif), Selbstständige und Familien, die beim Kind bleiben wollen. Voraussetzung ist eine gesetzliche Krankenversicherung.' } }
      ]
    },
  },
  {
    path: '/leistungen',
    title: 'Versicherungen: Ambulant, Zahn, Klinik & Tier | Healio',
    description: 'Wähle den passenden Schutzbereich: ambulant, Zahn, stationär oder Tier. Healio erklärt Leistungen und Grenzen verständlich und unabhängig.',
    canonical: 'https://healio.de/leistungen',
    lang: 'de',
    hreflang: { de: 'https://healio.de/leistungen', en: 'https://healio.de/en/services' },
  },
  {
    path: '/about',
    title: 'Über Healio – Versicherung verständlich begleitet',
    description: 'Die Healio GmbH verbindet unabhängige Versicherungsberatung mit einem Partnernetzwerk für Praxen und Unternehmen – verständlich, persönlich und digital begleitet.',
    canonical: 'https://healio.de/about',
    lang: 'de',
    hreflang: { de: 'https://healio.de/about', en: 'https://healio.de/en/about' },
  },
  {
    path: '/kontakt',
    title: 'Kontakt für Privatpersonen und Praxen | Healio',
    description: 'Fragen zu Kassenboni und Zusatzversicherungen? Healio berät Privatpersonen und informiert Praxen über die Zusammenarbeit.',
    canonical: 'https://healio.de/kontakt',
    lang: 'de',
    hreflang: { de: 'https://healio.de/kontakt', en: 'https://healio.de/en/contact' },
    ogImage: 'https://healio.de/images/healio-app-icon.png',
    ogImageAlt: 'Healio – Figur mit Blatt',
    ogImageWidth: 1024,
    ogImageHeight: 1024,
  },
  {
    path: '/blog',
    title: 'Healio Ratgeber – Gesundheitsbudget, Naturheilkunde & Zusatzversicherung',
    description: 'Expertenwissen zu Gesundheitsbudget, Heilpraktiker-Kosten, IKK Bonus, Naturheilkunde-Erstattung und Zusatzversicherungen.',
    canonical: 'https://healio.de/blog',
    lang: 'de',
    hreflang: { de: 'https://healio.de/blog', en: 'https://healio.de/en/blog' },
  },
  {
    path: '/ratgeber',
    title: 'Ratgeber zu Krankenkasse, Bonus und Zusatzschutz | Healio',
    description: 'Verständliche Ratgeber von Healio zu Kassenbonus, ambulanter Zusatzversicherung und Zahnschutz. Erst prüfen, was die eigene Kasse zahlt, dann entscheiden.',
    canonical: 'https://healio.de/ratgeber',
    lang: 'de',
    schemaMarkup: {
      '@context': 'https://schema.org',
      '@type': 'WebPage',
      '@id': 'https://healio.de/ratgeber#webpage',
      url: 'https://healio.de/ratgeber',
      name: 'Ratgeber zu Krankenkasse, Bonus und Zusatzschutz | Healio',
      description: 'Verständliche Ratgeber von Healio zu Kassenbonus, ambulanter Zusatzversicherung und Zahnschutz.',
      inLanguage: 'de-DE',
      isPartOf: { '@id': 'https://healio.de/#website' },
      about: { '@id': 'https://healio.de/#organization' },
    },
  },
  {
    path: '/blog/heilpraktiker-kosten-guide-2026',
    title: 'Heilpraktiker Kosten 2026: Preise, Erstattung & Budget | Healio',
    description: 'Was kostet ein Heilpraktiker 2026? Preise, Beispiele und Wege zur Erstattung durch Zusatzversicherung und Gesundheitsbudget.',
    canonical: 'https://healio.de/blog/heilpraktiker-kosten-guide-2026',
    lang: 'de',
  },
  {
    path: '/blog/heilpraktiker-zusatzversicherung-vergleich-2026',
    title: 'Heilpraktiker Zusatzversicherung Vergleich 2026 | Healio',
    description: 'Heilpraktiker Zusatzversicherung 2026: Welche Leistungen wichtig sind, welche Grenzen es gibt und wie du Erstattung mit Kassenbonus planst.',
    canonical: 'https://healio.de/blog/heilpraktiker-zusatzversicherung-vergleich-2026',
    lang: 'de',
  },
  {
    path: '/blog/ikk-classic-bonus-700-euro',
    title: 'IKK Classic Bonus 700 €+: So nutzt du den Kassenbonus | Healio',
    description: 'So funktioniert der IKK Classic Bonus mit 700 €+ pro Jahr: Aktivitäten, Nachweise und Kombination mit dem Healio Gesundheitsbudget.',
    canonical: 'https://healio.de/blog/ikk-classic-bonus-700-euro',
    lang: 'de',
  },
  {
    path: '/blog/osteopathie-krankenkasse-2026',
    title: 'Osteopathie Krankenkasse 2026: Erstattung & Budget | Healio',
    description: 'Welche Krankenkasse zahlt Osteopathie? Überblick zu Zuschüssen, Grenzen und dem 3.000 € Gesundheitsbudget über Healio.',
    canonical: 'https://healio.de/blog/osteopathie-krankenkasse-2026',
    lang: 'de',
  },
  {
    path: '/blog/naturheilkunde-krankenkasse-2026',
    title: 'Naturheilkunde Krankenkasse 2026: Was wird erstattet? | Healio',
    description: 'Naturheilkunde, Akupunktur, TCM und Heilpraktiker: Was gesetzliche Krankenkassen zahlen und wie ein Gesundheitsbudget hilft.',
    canonical: 'https://healio.de/blog/naturheilkunde-krankenkasse-2026',
    lang: 'de',
  },
  {
    path: '/blog/gesundheitsbudget-3000-euro',
    title: '3.000 € Gesundheitsbudget: Kassenbonus + Zusatzversicherung | Healio',
    description: 'Wie du bis zu 3.000 € Gesundheitsbudget in 2 Jahren nutzt: Kassenbonus, Zusatzversicherung und Erstattung für Naturheilkunde.',
    canonical: 'https://healio.de/blog/gesundheitsbudget-3000-euro',
    lang: 'de',
  },
  {
    path: '/potenzialanalyse',
    title: 'Potenzialanalyse für KassenBoost, bAV und bKV | Healio',
    description: 'Kostenlose Potenzialanalyse für KassenBoost als Mitarbeiterzugang, betriebliche Altersvorsorge (bAV), bKV oder ein integriertes Gesamtsystem.',
    canonical: 'https://healio.de/potenzialanalyse',
    lang: 'de',
    hreflang: { de: 'https://healio.de/potenzialanalyse', en: 'https://healio.de/en/potential-analysis' },
    schemaMarkup: {
      '@context': 'https://schema.org',
      '@type': 'WebPage',
      '@id': 'https://healio.de/potenzialanalyse#webpage',
      url: 'https://healio.de/potenzialanalyse',
      name: 'Potenzialanalyse für KassenBoost, bAV und bKV | Healio',
      description: 'Kostenlose Potenzialanalyse für KassenBoost als Mitarbeiterzugang, betriebliche Altersvorsorge (bAV), bKV oder ein integriertes Gesamtsystem.',
      inLanguage: 'de-DE',
      isPartOf: { '@id': 'https://healio.de/#website' },
      about: { '@id': 'https://healio.de/#organization' },
    },
  },
  {
    path: '/terminvereinbarung',
    title: 'Termin vereinbaren – Kostenlose Beratung | Healio',
    description: 'Vereinbaren Sie jetzt einen kostenlosen Beratungstermin bei Healio. Persönliche Beratung zu Gesundheitsbudget und Zusatzversicherungen.',
    canonical: 'https://healio.de/terminvereinbarung',
    lang: 'de',
    hreflang: { de: 'https://healio.de/terminvereinbarung', en: 'https://healio.de/en/appointment' },
  },
  {
    path: '/confirmation',
    title: 'Bestätigung | Healio',
    description: 'Vielen Dank für Ihre Anfrage bei Healio.',
    canonical: 'https://healio.de/confirmation',
    lang: 'de',
    robots: 'noindex, nofollow',
  },
  {
    path: '/tierkrankenversicherung',
    title: 'Tierkrankenversicherung – Schutz für Hund & Katze | Healio',
    description: 'Tierkrankenversicherung für Hund und Katze: OP-Schutz, Krankenvollversicherung, schnelle Erstattung. Jetzt Tarife vergleichen.',
    canonical: 'https://healio.de/tierkrankenversicherung',
    lang: 'de',
    hreflang: { de: 'https://healio.de/tierkrankenversicherung', en: 'https://healio.de/en/pet-insurance' },
  },
  {
    path: '/presse',
    title: 'Presse und Fakten zur Healio GmbH | Healio',
    description: 'Faktenblatt der Healio GmbH für Redaktionen: Kurzprofil, Zahlen und Fakten zum Gesundheitsbudget, Gründerprofil, Pressekontakt und Logodateien zum Download.',
    canonical: 'https://healio.de/presse',
    keywords: 'Healio Presse, Healio Pressekontakt, Healio Faktenblatt, Healio GmbH Hamburg, Gesundheitsbudget Fakten',
    lang: 'de',
    schemaMarkup: {
      '@context': 'https://schema.org',
      '@type': 'WebPage',
      '@id': 'https://healio.de/presse#webpage',
      url: 'https://healio.de/presse',
      name: 'Presse und Fakten zur Healio GmbH | Healio',
      description: 'Faktenblatt der Healio GmbH für Redaktionen: Kurzprofil, Zahlen und Fakten zum Gesundheitsbudget, Gründerprofil, Pressekontakt und Logodateien zum Download.',
      inLanguage: 'de-DE',
      isPartOf: { '@id': 'https://healio.de/#website' },
      about: { '@id': 'https://healio.de/#organization' },
    },
  },
  {
    path: '/impressum',
    title: 'Impressum | Healio GmbH',
    description: 'Impressum der Healio GmbH, Hamburg. Anbieterangaben gemäß § 5 DDG.',
    canonical: 'https://healio.de/impressum',
    lang: 'de',
    hreflang: { de: 'https://healio.de/impressum', en: 'https://healio.de/en/legal-notice' },
  },
  {
    path: '/agb',
    title: 'AGB – Allgemeine Geschäftsbedingungen | Healio',
    description: 'Allgemeine Geschäftsbedingungen der Healio GmbH.',
    canonical: 'https://healio.de/agb',
    lang: 'de',
    hreflang: { de: 'https://healio.de/agb', en: 'https://healio.de/en/terms' },
  },
  {
    path: '/datenschutz',
    title: 'Datenschutzerklärung | Healio GmbH',
    description: 'Datenschutzerklärung der Healio GmbH. Informationen zum Umgang mit personenbezogenen Daten.',
    canonical: 'https://healio.de/datenschutz',
    lang: 'de',
    hreflang: { de: 'https://healio.de/datenschutz', en: 'https://healio.de/en/privacy' },
  },
  {
    path: '/erstinformation',
    title: 'Erstinformation für Versicherungsnehmer | Healio',
    description: 'Erstinformation der Healio GmbH gemäß §§ 15 und 16 VersVermV mit Vermittlerstatus, Vergütung, Registerangaben, Schlichtungsstellen und Beratungsgrundlage nach § 60 VVG.',
    canonical: 'https://healio.de/erstinformation',
    lang: 'de',
    hreflang: { de: 'https://healio.de/erstinformation', en: 'https://healio.de/en/initial-information' },
  },

  // === BLOG-ARTIKEL (Heilpraktiker-Zielgruppe) ===
  {
    path: '/blog/heilpraktiker-patienten-finanzierung-gesundheitsbudget',
    title: 'Heilpraktiker-Kostenübernahme: 3.000 EUR Budget | Healio',
    description: 'Bis zu 3.000 EUR Gesundheitsbudget in 2 Jahren für Naturheilverfahren. Ein passender Kassenbonus kann den Beitrag individuell bis zu 100 % reduzieren.',
    canonical: 'https://healio.de/blog/heilpraktiker-patienten-finanzierung-gesundheitsbudget',
    lang: 'de',
  },
  {
    path: '/blog/digitale-erstattung-heilpraktiker-rechnungen-zusatzversicherung',
    title: 'Heilpraktiker Abrechnung vereinfachen: Digitale Erstattung App | Healio',
    description: 'Rechnungen digital einreichen und Erstattungen verfolgen. Bis zu 3.000 EUR Gesundheitsbudget in 2 Jahren sind tarifabhängig möglich.',
    canonical: 'https://healio.de/blog/digitale-erstattung-heilpraktiker-rechnungen-zusatzversicherung',
    lang: 'de',
  },
  {
    path: '/blog/heilpraktiker-kosten-gkv-erstattung-healio',
    title: 'Heilpraktiker-Kosten GKV: Warum alles selbst zahlen + Lösung | Healio',
    description: 'Was die GKV bei Heilpraktiker-Kosten leistet und wie Zusatzschutz bis zu 3.000 EUR Gesundheitsbudget in 2 Jahren ermöglichen kann.',
    canonical: 'https://healio.de/blog/heilpraktiker-kosten-gkv-erstattung-healio',
    lang: 'de',
  },
  {
    path: '/blog/zahnzusatzversicherung-trotz-angeratener-behandlung',
    title: 'Zahnzusatzversicherung trotz angeratener Behandlung: Sofortschutz | Healio',
    description: 'Behandlung schon angeraten? Der Baustein ZAHN Sofort der Bayerischen zahlt bis zu 1.500 € Zuschuss, wenn der Abschluss vor der Rechnung erfolgt.',
    canonical: 'https://healio.de/blog/zahnzusatzversicherung-trotz-angeratener-behandlung',
    lang: 'de',
  },
  {
    path: '/blog/krankenhauszusatzversicherung-sportverein-best-ager',
    title: 'Krankenhauszusatzversicherung ab 50: Sportverein zahlt sich doppelt aus | Healio',
    description: 'Fit im Sportverein? Dann bekommst du den Klinik-Tarif leichter und der IKK Bonus kann den Beitrag bis zu 100 % refinanzieren.',
    canonical: 'https://healio.de/blog/krankenhauszusatzversicherung-sportverein-best-ager',
    lang: 'de',
  },
  {
    path: '/blog/healio-konzept-fuer-heilpraktiker',
    title: 'Das Healio-Konzept für Heilpraktiker | Healio',
    description: 'Therapieabbrüche wegen Geld? Das Healio-Konzept gibt deinen Patienten bis zu 3.000 € Gesundheitsbudget für Naturheilkunde.',
    canonical: 'https://healio.de/blog/healio-konzept-fuer-heilpraktiker',
    lang: 'de',
  },
  {
    path: '/blog/healio-konzept-fuer-osteopathen',
    title: 'Das Healio-Konzept für Osteopathen | Healio',
    description: 'Kassen streichen Osteopathie-Zuschüsse. Das Healio-Konzept gibt deinen Patienten bis zu 3.000 € Budget, IKK-Bonus inklusive.',
    canonical: 'https://healio.de/blog/healio-konzept-fuer-osteopathen',
    lang: 'de',
  },
  {
    path: '/blog/healio-konzept-fuer-tcm-praxen',
    title: 'Das Healio-Konzept für TCM-Praxen | Healio',
    description: 'GKV zahlt Akupunktur nur in Ausnahmen. Das Healio-Konzept gibt deinen Patienten bis zu 3.000 € Budget für TCM beim Heilpraktiker.',
    canonical: 'https://healio.de/blog/healio-konzept-fuer-tcm-praxen',
    lang: 'de',
  },
  {
    path: '/blog/healio-konzept-fuer-hebammen',
    title: 'Das Healio-Konzept für Hebammen | Healio',
    description: 'Werdende Eltern vertrauen deiner Empfehlung. Das Healio-Konzept bringt Familien bis zu 3.000 € Gesundheitsbudget plus Vorsorge-Topf.',
    canonical: 'https://healio.de/blog/healio-konzept-fuer-hebammen',
    lang: 'de',
  },
  {
    path: '/blog/kassenbonus-was-ist-drin',
    title: 'Kassenbonus: Was ist das, und wie viel ist wirklich drin? | Healio',
    description: 'Kassenbonus einfach erklärt: Definition, IKK-Beispiel bis zu 1.155 EUR und wie dein Bonus zum Zuschuss für deinen Zusatzschutz wird.',
    canonical: 'https://healio.de/blog/kassenbonus-was-ist-drin',
    lang: 'de',
  },
  {
    path: '/blog/krankenkasse-wechseln-laufende-behandlung',
    title: 'Krankenkasse wechseln: Was passiert mit laufenden Behandlungen? | Healio',
    description: 'Krankenkasse wechseln und trotzdem Leistungen, Genehmigungen und Hilfsmittel behalten: Was du vorher klären solltest.',
    canonical: 'https://healio.de/blog/krankenkasse-wechseln-laufende-behandlung',
    lang: 'de',
  },
  {
    path: '/blog/heilpraktiker-kosten-bonus-finanziert',
    title: 'Heilpraktiker-Kosten: Kassenbonus finanziert Zusatzversicherung | Healio',
    description: 'Heilpraktiker sind Selbstzahlerleistung. So finanziert eine ambulante Zusatzversicherung den Beitrag, und dein Kassenbonus kann ihn zurückholen.',
    canonical: 'https://healio.de/blog/heilpraktiker-kosten-bonus-finanziert',
    lang: 'de',
  },
  {
    path: '/blog/zahnersatz-beitrag-vom-bonus',
    title: 'Zahnersatz: Beitrag der Zahnzusatzversicherung vom Bonus tragen | Healio',
    description: 'Zahnersatz kostet mehr, als die Kasse zahlt. Zahnzusatz ab rund 10 EUR im Monat, und dein Kassenbonus kann den Beitrag ausgleichen.',
    canonical: 'https://healio.de/blog/zahnersatz-beitrag-vom-bonus',
    lang: 'de',
  },
  {
    path: '/blog/ikk-classic-bonus-schritt-fuer-schritt',
    title: 'IKK classic Bonus Schritt für Schritt | Healio',
    description: 'So holst du den IKK-classic-Bonus konkret ab: passende Aktivitäten, nötige Nachweise, Einreichfrist und wie du die Verwendung wählst.',
    canonical: 'https://healio.de/blog/ikk-classic-bonus-schritt-fuer-schritt',
    lang: 'de',
  },
  {
    path: '/blog/bkv-und-kassenbonus-fuer-arbeitgeber',
    title: 'Für Arbeitgeber: bKV und Kassenbonus als Paket | Healio',
    description: 'bKV als Sachbezug und der private Kassenbonus der Mitarbeiter ergänzen sich. So erklären Sie das Paket verständlich, ohne Mehraufwand für HR.',
    canonical: 'https://healio.de/blog/bkv-und-kassenbonus-fuer-arbeitgeber',
    lang: 'de',
  },
  {
    path: '/blog/kassenbonus-schwangerschaft-vorsorge',
    title: 'Kassenbonus in der Schwangerschaft: Mutterschaftsvorsorge | Healio',
    description: 'Warum Schwangere mehr Kassenbonus bekommen, welche IKK-Positionen zählen und wie der Zuschuss deinen Zusatzschutz mitfinanziert.',
    canonical: 'https://healio.de/blog/kassenbonus-schwangerschaft-vorsorge',
    lang: 'de',
  },
  {
    path: '/blog/hebammen-gesundheitsbudget-erklaeren',
    title: 'Für Hebammen: Gesundheitsbudget werdenden Eltern erklären | Healio',
    description: 'Was du als Hebamme zum Gesundheitsbudget sagen darfst, ohne zu beraten: bar bezahlte Leistungen, das Zeitfenster fürs Kind, dein Nutzen.',
    canonical: 'https://healio.de/blog/hebammen-gesundheitsbudget-erklaeren',
    lang: 'de',
  },

  // === ENGLISCH ===
  {
    path: '/en',
    title: 'Supplementary health insurance, made simple | Healio',
    description: 'Compare outpatient, dental and hospital supplementary insurance with clarity. Healio supports you digitally and personally, from selection to ongoing service.',
    canonical: 'https://healio.de/en',
    lang: 'en',
    hreflang: { de: 'https://healio.de', en: 'https://healio.de/en' },
  },
  {
    path: '/en/companies',
    title: 'Corporate Benefits Management | Pension, Health & Wellbeing | Healio',
    description: 'Healio combines corporate pension, health insurance, wellbeing coordination and employee communication into one managed benefits system.',
    canonical: 'https://healio.de/en/companies',
    ogImage: 'https://healio.de/images/healio-hero-markenrelief-v1.webp',
    ogImageWidth: 1586,
    ogImageHeight: 992,
    lang: 'en',
    hreflang: { de: 'https://healio.de/unternehmen', en: 'https://healio.de/en/companies' },
  },
  {
    path: '/en/kassenboost',
    title: 'Use your health fund bonus: from KassenBoost to Healio',
    description: 'Compared funds on KassenBoost? Healio shows you how to take your fund bonus as cash or triple it into supplementary cover. Free, independent, no data transfer.',
    canonical: 'https://healio.de/en/kassenboost',
    ogImage: 'https://healio.de/images/kassenboost-bridge-og.png',
    ogImageAlt: 'KassenBoost and Healio: compare, use your bonus, get covered',
    ogImageWidth: 1200,
    ogImageHeight: 630,
    lang: 'en',
    hreflang: { de: 'https://healio.de/kassenboost', en: 'https://healio.de/en/kassenboost' },
    schemaMarkup: {
      '@context': 'https://schema.org',
      '@type': 'WebPage',
      '@id': 'https://healio.de/en/kassenboost#webpage',
      url: 'https://healio.de/en/kassenboost',
      name: 'KassenBoost & Healio: Compare Health Funds Privately',
      description: 'Compare statutory health funds privately with KassenBoost. Then decide whether supplementary cover or a Healio employer offer is relevant to you.',
      inLanguage: 'en-US',
      isPartOf: { '@id': 'https://healio.de/#website' },
      about: { '@id': 'https://healio.de/#organization' },
    },
  },
  {
    path: '/en/health-insurance-bonus',
    title: 'Compare German Health Insurance Bonuses and Costs | Healio',
    description: 'Compare German statutory health insurers by contribution, realistic bonus and relevant extra benefits before making a decision.',
    canonical: 'https://healio.de/en/health-insurance-bonus',
    keywords: 'German health insurance comparison, statutory health insurance bonus, Krankenkasse contribution, health insurance benefits Germany',
    lang: 'en',
    hreflang: { de: 'https://healio.de/kassenbonus', en: 'https://healio.de/en/health-insurance-bonus' },
  },
  {
    path: '/en/outpatient',
    title: 'Outpatient Supplementary Insurance – Up to 3,000 € Health Budget | Healio',
    description: 'Up to 3,000 € health budget for naturopathy, osteopathy & alternative medicine. Smart combination of health insurance bonuses.',
    canonical: 'https://healio.de/en/outpatient',
    lang: 'en',
    hreflang: { de: 'https://healio.de/ambulant', en: 'https://healio.de/en/outpatient' },
  },
  {
    path: '/en/partner',
    title: 'For Practices – Explain Health Budgets Clearly | Healio',
    description: 'A free partnership for naturopaths, osteopaths and midwives: The practice provides information while Healio independently reviews and advises patients.',
    canonical: 'https://healio.de/en/partner',
    lang: 'en',
    hreflang: { de: 'https://healio.de/partner', en: 'https://healio.de/en/partner' },
  },
  {
    path: '/en/healthcare-professionals-protection',
    title: 'Healthcare Professional Coverage for Naturopaths and Osteopaths | Healio',
    description: 'Bundled coverage for your practice and your life: professional liability, practice interruption, cyber, disability insurance and Rürup pension.',
    canonical: 'https://healio.de/en/healthcare-professionals-protection',
    lang: 'en',
    hreflang: { de: 'https://healio.de/heilberufe-vorsorge', en: 'https://healio.de/en/healthcare-professionals-protection' },
  },
  {
    path: '/en/dental',
    title: 'Dental Insurance – Up to 100% Coverage | Healio',
    description: 'Dental supplementary insurance with up to 100% coverage for dental prosthetics, prophylaxis and orthodontics.',
    canonical: 'https://healio.de/en/dental',
    lang: 'en',
    hreflang: { de: 'https://healio.de/zahn', en: 'https://healio.de/en/dental' },
  },
  {
    path: '/en/inpatient',
    title: 'Hospital Supplementary Insurance: Private Patient in Hospital | Healio',
    description: 'Hospital supplementary insurance: private room, chief physician treatment, free hospital choice. SDK hospital plans, e.g. from EUR 7.00/month (SPU, age 30).',
    canonical: 'https://healio.de/en/inpatient',
    lang: 'en',
    hreflang: { de: 'https://healio.de/stationaer', en: 'https://healio.de/en/inpatient' },
  },
  {
    path: '/en/services',
    title: 'Insurance: Outpatient, Dental, Hospital & Pet | Healio',
    description: 'Choose the right area of cover: outpatient, dental, hospital or pet. Healio explains benefits and limits clearly and independently.',
    canonical: 'https://healio.de/en/services',
    lang: 'en',
    hreflang: { de: 'https://healio.de/leistungen', en: 'https://healio.de/en/services' },
  },
  {
    path: '/en/about',
    title: 'About Healio – Insurance, Clearly Guided',
    description: 'Healio GmbH combines independent insurance advice with a partner network for practices and companies – clear, personal and digitally supported.',
    canonical: 'https://healio.de/en/about',
    lang: 'en',
    hreflang: { de: 'https://healio.de/about', en: 'https://healio.de/en/about' },
  },
  {
    path: '/en/contact',
    title: 'Contact for individuals and practices | Healio',
    description: 'Questions about health insurance bonuses and supplementary insurance? Healio supports individuals and informs practices about working together.',
    canonical: 'https://healio.de/en/contact',
    lang: 'en',
    hreflang: { de: 'https://healio.de/kontakt', en: 'https://healio.de/en/contact' },
    ogImage: 'https://healio.de/images/healio-app-icon.png',
    ogImageAlt: 'Healio – Figur mit Blatt',
    ogImageWidth: 1024,
    ogImageHeight: 1024,
  },
  {
    path: '/en/initial-information',
    title: 'Initial information for insurance customers | Healio',
    description: 'Initial information from Healio GmbH pursuant to §§ 15 and 16 VersVermV, including intermediary status, remuneration, register details, dispute resolution bodies and the basis of advice under section 60 VVG.',
    canonical: 'https://healio.de/en/initial-information',
    lang: 'en',
    hreflang: { de: 'https://healio.de/erstinformation', en: 'https://healio.de/en/initial-information' },
  },
  {
    path: '/en/blog',
    title: 'Healio Guide – Health Budget, Naturopathy & Insurance',
    description: 'Expert knowledge on health budgets, practitioner costs, insurance bonuses and supplementary coverage.',
    canonical: 'https://healio.de/en/blog',
    lang: 'en',
    hreflang: { de: 'https://healio.de/blog', en: 'https://healio.de/en/blog' },
    robots: 'noindex, nofollow',
  },
  {
    path: '/en/midwives',
    title: 'For Midwives – Health Budget for Families | Healio',
    description: 'Healio partner programme for midwives: relieve families financially, make courses easier to afford and inform parents on a legally safe basis.',
    canonical: 'https://healio.de/en/midwives',
    lang: 'en',
    hreflang: { de: 'https://healio.de/hebammen', en: 'https://healio.de/en/midwives' },
  },
  {
    path: '/en/appointment',
    title: 'Book an Appointment – Free Consultation | Healio',
    description: 'Book a free consultation with Healio. Personal advice on health budgets and supplementary health insurance.',
    canonical: 'https://healio.de/en/appointment',
    lang: 'en',
    hreflang: { de: 'https://healio.de/terminvereinbarung', en: 'https://healio.de/en/appointment' },
  },
  {
    path: '/en/potential-analysis',
    title: 'Potential analysis for KassenBoost, pension and health | Healio',
    description: 'Free potential analysis for KassenBoost employee access, corporate pension, corporate health insurance or an integrated benefits system.',
    canonical: 'https://healio.de/en/potential-analysis',
    lang: 'en',
    hreflang: { de: 'https://healio.de/potenzialanalyse', en: 'https://healio.de/en/potential-analysis' },
    schemaMarkup: {
      '@context': 'https://schema.org',
      '@type': 'WebPage',
      '@id': 'https://healio.de/en/potential-analysis#webpage',
      url: 'https://healio.de/en/potential-analysis',
      name: 'Potential analysis for KassenBoost, pension and health | Healio',
      description: 'Free potential analysis for KassenBoost employee access, corporate pension, corporate health insurance or an integrated benefits system.',
      inLanguage: 'en-US',
      isPartOf: { '@id': 'https://healio.de/#website' },
      about: { '@id': 'https://healio.de/#organization' },
    },
  },
  {
    path: '/en/pet-insurance',
    title: 'Pet Health Insurance – Cover for Dogs & Cats | Healio',
    description: 'Pet health insurance for dogs and cats: surgery cover, full health cover and fast reimbursement. Compare plans now.',
    canonical: 'https://healio.de/en/pet-insurance',
    lang: 'en',
    hreflang: { de: 'https://healio.de/tierkrankenversicherung', en: 'https://healio.de/en/pet-insurance' },
  },
  {
    path: '/en/legal-notice',
    title: 'Legal Notice | Healio GmbH',
    description: 'Legal notice of Healio GmbH, Hamburg. Provider information pursuant to section 5 DDG.',
    canonical: 'https://healio.de/en/legal-notice',
    lang: 'en',
    hreflang: { de: 'https://healio.de/impressum', en: 'https://healio.de/en/legal-notice' },
  },
  {
    path: '/en/terms',
    title: 'Terms and Conditions | Healio',
    description: 'General terms and conditions of Healio GmbH.',
    canonical: 'https://healio.de/en/terms',
    lang: 'en',
    hreflang: { de: 'https://healio.de/agb', en: 'https://healio.de/en/terms' },
  },
  {
    path: '/en/privacy',
    title: 'Privacy Policy | Healio GmbH',
    description: 'Privacy policy of Healio GmbH. Information on how personal data is processed.',
    canonical: 'https://healio.de/en/privacy',
    lang: 'en',
    hreflang: { de: 'https://healio.de/datenschutz', en: 'https://healio.de/en/privacy' },
  },

  {
    path: '/partner/leitfaden',
    title: 'Der Therapieabbruch-Stopper: Leitfaden für Naturheilpraxen | Healio',
    description: 'Kostenloser Leitfaden für Naturheilpraxen: wie aus Kassenbonus und Zusatzschutz bis zu 3.000 EUR Gesundheitsbudget in zwei Jahren werden und wie der Ablauf in fünf Schritten aussieht.',
    canonical: 'https://healio.de/partner/leitfaden',
    keywords: 'Leitfaden Naturheilpraxis, Gesundheitsbudget Praxis, Therapieabbruch verhindern, Selbstzahler Heilpraktiker, Kassenbonus Zusatzversicherung',
    lang: 'de',
    schemaMarkup: {
      '@context': 'https://schema.org',
      '@type': 'WebPage',
      '@id': 'https://healio.de/partner/leitfaden#webpage',
      url: 'https://healio.de/partner/leitfaden',
      name: 'Der Therapieabbruch-Stopper: Leitfaden für Naturheilpraxen',
      description: 'Kostenloser Leitfaden für Naturheilpraxen zum Gesundheitsbudget aus Kassenbonus und Zusatzschutz.',
      inLanguage: 'de-DE',
      isPartOf: { '@id': 'https://healio.de/#website' },
      about: { '@id': 'https://healio.de/#organization' },
    },
  },

  // === FUNKTIONS- UND KAMPAGNENSEITEN (nicht für den Index bestimmt) ===
  // Diese Routen existieren im Router, sollen aber nicht in die Google-Suche.
  // Ohne eigenen Eintrag liefert der Vercel-Catch-all sonst die Startseite
  // samt Startseiten-Canonical aus -> Search Console meldet
  // "Alternative Seite mit richtigem kanonischen Tag".
  {
    path: '/partner/leitfaden/danke',
    title: 'Dein Leitfaden ist da | Healio',
    description: 'Bestätigungsseite nach der Anforderung des Praxis-Leitfadens. Download des PDF und Terminwahl für den Praxis-Check.',
    canonical: 'https://healio.de/partner/leitfaden/danke',
    lang: 'de',
    robots: 'noindex, nofollow',
  },
  {
    path: '/lebenshilfe',
    title: 'Betriebliche Vorsorge für die Lebenshilfe | Healio',
    description: 'Informationsseite zur betrieblichen Vorsorge für die Lebenshilfe.',
    canonical: 'https://healio.de/lebenshilfe',
    lang: 'de',
    robots: 'noindex, nofollow',
  },
  {
    path: '/unternehmen/vorsorge-rechner',
    title: 'bAV-Entscheidungsrechner 2026 | Healio',
    description: 'Arbeitgeberfinanzierte bAV mit 2026er Beitragsgrenzen, Sozialabgaben und Kapitalprojektion transparent modellieren.',
    canonical: 'https://healio.de/unternehmen/vorsorge-rechner',
    lang: 'de',
    hreflang: {
      de: 'https://healio.de/unternehmen/vorsorge-rechner',
      en: 'https://healio.de/en/companies/pension-calculator',
    },
    robots: 'noindex, nofollow',
    schemaMarkup: {
      '@context': 'https://schema.org',
      '@type': 'WebPage',
      '@id': 'https://healio.de/unternehmen/vorsorge-rechner#webpage',
      url: 'https://healio.de/unternehmen/vorsorge-rechner',
      name: 'bAV-Entscheidungsrechner 2026 | Healio',
      description: 'Arbeitgeberfinanzierte bAV mit 2026er Beitragsgrenzen, Sozialabgaben und Kapitalprojektion transparent modellieren.',
      inLanguage: 'de-DE',
      isPartOf: { '@id': 'https://healio.de/#website' },
      about: { '@id': 'https://healio.de/#organization' },
    },
  },
  {
    path: '/en/companies/pension-calculator',
    title: 'Employer pension decision calculator 2026 | Healio',
    description: 'Model employer-funded pension contributions with 2026 contribution ceilings, social charges and a transparent capital projection.',
    canonical: 'https://healio.de/en/companies/pension-calculator',
    lang: 'en',
    hreflang: {
      de: 'https://healio.de/unternehmen/vorsorge-rechner',
      en: 'https://healio.de/en/companies/pension-calculator',
    },
    robots: 'noindex, nofollow',
    schemaMarkup: {
      '@context': 'https://schema.org',
      '@type': 'WebPage',
      '@id': 'https://healio.de/en/companies/pension-calculator#webpage',
      url: 'https://healio.de/en/companies/pension-calculator',
      name: 'Employer pension decision calculator 2026 | Healio',
      description: 'Model employer-funded pension contributions with 2026 contribution ceilings, social charges and a transparent capital projection.',
      inLanguage: 'en-US',
      isPartOf: { '@id': 'https://healio.de/#website' },
      about: { '@id': 'https://healio.de/#organization' },
    },
  },
  {
    // Advertorial fuer bezahlte Meta-Besucher. Bewusst nicht im Index:
    // die Seite ist Werbung, nicht organische Sichtbarkeit. Die Uebersicht
    // /ratgeber und spaetere organische Ratgeberartikel bleiben indexiert.
    path: '/ratgeber/krankenkassen-bonus-zusatzversicherung',
    title: 'Krankenkassen-Bonus nutzen und Zusatzschutz finanzieren | Healio',
    description: 'Wie das Bonusprogramm der eigenen gesetzlichen Krankenkasse den größten Teil einer ambulanten Zusatzversicherung trägt. Erst prüfen, dann entscheiden.',
    canonical: 'https://healio.de/ratgeber/krankenkassen-bonus-zusatzversicherung',
    lang: 'de',
    robots: 'noindex, nofollow',
  },
  {
    path: '/zahnaerzte/praxis-checkliste',
    title: 'Praxis-Checkliste für Zahnarztpraxen | Healio',
    description: 'B2B-Arbeitsunterlage mit fünf Konzeptgrenzen für sachliche Patienteninformation in Zahnarztpraxen.',
    canonical: 'https://healio.de/zahnaerzte/praxis-checkliste',
    lang: 'de',
    robots: 'noindex, nofollow',
  },
  {
    path: '/konto-loeschen',
    title: 'Konto löschen | Healio',
    description: 'Löschung des Healio-App-Kontos beantragen.',
    canonical: 'https://healio.de/konto-loeschen',
    lang: 'de',
    robots: 'noindex, follow',
  },
  {
    path: '/app-bestaetigt',
    title: 'E-Mail-Adresse bestätigt | Healio',
    description: 'Die E-Mail-Adresse für die Healio App wurde bestätigt.',
    canonical: 'https://healio.de/app-bestaetigt',
    lang: 'de',
    robots: 'noindex, nofollow',
  },
  {
    path: '/reset-password',
    title: 'Passwort zurücksetzen | Healio',
    description: 'Passwort für die Healio App zurücksetzen.',
    canonical: 'https://healio.de/reset-password',
    lang: 'de',
    robots: 'noindex, nofollow',
  },
  {
    path: '/en/confirmation',
    title: 'Confirmation | Healio',
    description: 'Thank you for your enquiry to Healio.',
    canonical: 'https://healio.de/en/confirmation',
    lang: 'en',
    robots: 'noindex, nofollow',
  },
  {
    path: '/tiktok',
    title: 'Healio auf TikTok | Healio',
    description: 'Alle Healio-Links aus der TikTok-Bio auf einen Blick.',
    canonical: 'https://healio.de/tiktok',
    lang: 'de',
    robots: 'noindex, follow',
  },
  {
    path: '/en/tiktok',
    title: 'Healio on TikTok | Healio',
    description: 'All Healio links from the TikTok bio at a glance.',
    canonical: 'https://healio.de/en/tiktok',
    lang: 'en',
    robots: 'noindex, follow',
  },
  {
    path: '/instagram',
    title: 'Healio auf Instagram | Healio',
    description: 'Alle Healio-Links aus der Instagram-Bio auf einen Blick.',
    canonical: 'https://healio.de/instagram',
    lang: 'de',
    robots: 'noindex, follow',
  },
  {
    path: '/en/instagram',
    title: 'Healio on Instagram | Healio',
    description: 'All Healio links from the Instagram bio at a glance.',
    canonical: 'https://healio.de/en/instagram',
    lang: 'en',
    robots: 'noindex, follow',
  },
];
