export const healioSoftClayIcons = Object.freeze({
  'ambulant-care': '/images/icons/healio-clay/ambulant-care.webp',
  'dental-protection': '/images/icons/healio-clay/dental-protection.webp',
  'hospital-comfort': '/images/icons/healio-clay/hospital-comfort.webp',
  'protection-path': '/images/icons/healio-clay/protection-path.webp',
  'clear-comparison': '/images/icons/healio-clay/clear-comparison.webp',
  'digital-completion': '/images/icons/healio-clay/digital-completion.webp',
  'personal-support': '/images/icons/healio-clay/personal-support.webp',
  'independent-guidance': '/images/icons/healio-clay/independent-guidance.webp',
  'ongoing-service': '/images/icons/healio-clay/ongoing-service.webp',
  'pension-growth': '/images/icons/healio-clay/pension-growth.webp',
  'health-budget': '/images/icons/healio-clay/health-budget.webp',
  'prevention-care': '/images/icons/healio-clay/prevention-care.webp',
  'concept-calculator': '/images/icons/healio-clay/concept-calculator.webp',
  'team-introduction': '/images/icons/healio-clay/team-introduction.webp',
  'business-expense': '/images/icons/healio-clay/business-expense.webp',
  'bonus-reward': '/images/icons/healio-clay/bonus-reward.webp',
  'family-care': '/images/icons/healio-clay/family-care.webp',
  'document-check': '/images/icons/healio-clay/document-check.webp',
  'planet-care': '/images/icons/healio-clay/planet-care.webp',
  'active-wellbeing': '/images/icons/healio-clay/active-wellbeing.webp',
  'pet-care': '/images/icons/healio-clay/pet-care.webp',
});

// Verbindlicher gemeinsamer Inhalts-Icon-Satz für Healio und KassenBoost.
// Die bestehenden Soft-Clay-IDs bleiben als rückwärtskompatible API erhalten.
export const friendlyIconAssets = Object.freeze({
  money: '/images/friendly-icons/money-note.webp',
  bonus: '/images/friendly-icons/bonus-medal.webp',
  budget: '/images/friendly-icons/health-wallet.webp',
  calculator: '/images/friendly-icons/calculator.webp',
  family: '/images/friendly-icons/family.webp',
  fitness: '/images/friendly-icons/fitness.webp',
  smartwatch: '/images/friendly-icons/smartwatch.webp',
  ambulant: '/images/friendly-icons/medical-stethoscope.webp',
  dental: '/images/friendly-icons/dental-shield.webp',
  hospital: '/images/friendly-icons/hospital-room.webp',
  support: '/images/friendly-icons/trust-broker-headset.webp',
  document: '/images/friendly-icons/document-check.webp',
  mandate: '/images/friendly-icons/tariff-review-advisor-v1.webp',
  region: '/images/friendly-icons/germany-region.webp',
  protection: '/images/friendly-icons/protection-shield.webp',
  comparison: '/images/friendly-icons/compare-value.webp',
  switch: '/images/friendly-icons/switch-check.webp',
  privacy: '/images/friendly-icons/privacy-lock.webp',
  calendar: '/images/friendly-icons/verified-calendar.webp',
  glasses: '/images/friendly-icons/vision-glasses.webp',
  pregnancy: '/images/friendly-icons/pregnancy.webp',
  prevention: '/images/friendly-icons/prevention-vaccination.webp',
  medication: '/images/friendly-icons/medication-copay.webp',
  naturopathy: '/images/friendly-icons/naturopathy.webp',
  thinking: '/images/friendly-icons/decision-thinking.webp',
  weighing: '/images/friendly-icons/decision-weighing.webp',
  choice: '/images/friendly-icons/decision-choice.webp',
  broker: '/images/friendly-icons/trust-broker.webp',
  advisor: '/images/friendly-icons/trust-advisor.webp',
  pet: '/images/friendly-icons/pet-care.webp',
});

// Alte `icon=`-Aufrufe zeigen automatisch den neuen Standard. Wo kein
// semantisch passendes Motiv existiert (aktuell Tier), bleibt das alte Asset.
export const legacyIconKindAliases = Object.freeze({
  'ambulant-care': 'ambulant',
  'dental-protection': 'dental',
  'hospital-comfort': 'hospital',
  'protection-path': 'protection',
  'clear-comparison': 'comparison',
  'digital-completion': 'switch',
  'personal-support': 'support',
  'independent-guidance': 'broker',
  'ongoing-service': 'support',
  'pension-growth': 'money',
  'health-budget': 'budget',
  'prevention-care': 'prevention',
  'concept-calculator': 'calculator',
  'team-introduction': 'advisor',
  'business-expense': 'money',
  'bonus-reward': 'bonus',
  'family-care': 'family',
  'document-check': 'document',
  'planet-care': 'naturopathy',
  'active-wellbeing': 'fitness',
  'pet-care': 'pet',
});

export default healioSoftClayIcons;
